# Surprise-dimension discovery

Steps 1-2 of the plan:

1. **Split** 2026Q3 events that have both a preview and a realized return chronologically: the earliest 80% are **train**, the latest 20% **test**. Then sample 500 **discovery** events from train only, stratified by next-day abnormal return (`car1`) decile. The return is never shown to the LLM.
2. **Extract** a free-form list of surprises (results vs. preview expectations) for every discovery event.

Extraction appends to `data/surprise/discovery_extractions.jsonl` one event at a time, so re-running a cell resumes where it stopped and retries failures.

In [16]:
%load_ext autoreload
%autoreload 2

import pandas as pd

from suprise_dim import data
from suprise_dim import extraction

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## 1. Split

In [17]:
events = data.load_eligible_events(quarters=("2026Q3",))
events_by_id = {e["event_id"]: e for e in events}
print(f"{len(events)} eligible events")

1365 eligible events

In [18]:
# Creates the split once; afterwards it is loaded so the sample stays fixed.
# A split saved in the old discovery/holdout format (no "test" key) is rebuilt.
# Pass overwrite=True to save_split only if you really want a new sample.
split = data.load_split() if data.SPLIT_PATH.exists() else None
if split is None or "test" not in split:
    split = data.make_split(events, train_frac=0.8, n_discovery=500, seed=42)
    data.save_split(split, overwrite=True)

discovery = [events_by_id[eid] for eid in split["discovery"]]
print(
    f"{len(split['train'])} train, {len(split['test'])} test (from {split['test_start']}), "
    f"{len(discovery)} discovery sampled from train (seed {split['seed']})"
)

1076 train, 289 test (from 2026-08-13T21:00:00+00:00), 500 discovery sampled from train (seed 42)

In [19]:
# Sanity check: date ranges must not overlap, and return distributions should be similar.
def describe(ids):
    evs = [events_by_id[eid] for eid in ids]
    s = pd.Series([data.car1(e) for e in evs]).describe()
    s["first"] = min(e["event_datetime"] for e in evs)
    s["last"] = max(e["event_datetime"] for e in evs)
    return s

assert set(split["discovery"]) <= set(split["train"])
pd.DataFrame({name: describe(split[name]) for name in ("train", "test", "discovery")})

,train,test,discovery
count,1076.0,289.0,500.0
mean,0.004312,-0.021619,0.006602
std,0.136077,0.14258,0.142161
min,-0.604792,-0.550218,-0.604792
25%,-0.065902,-0.102891,-0.066656
50%,0.001946,-0.012022,0.00162
75%,0.064677,0.043232,0.062681
max,0.649427,0.738772,0.649427
first,2026-08-03T12:00:00+00:00,2026-08-13T21:00:00+00:00,2026-08-03T12:30:00+00:00
last,2026-08-13T20:30:00+00:00,2026-09-22T21:00:00+00:00,2026-08-13T20:30:00+00:00

## 2. Extraction

### Inspect one event

Look at the prompt and a single result before spending on the full run.

In [20]:
from suprise_dim.prompts import EXTRACTION_SYSTEM, build_user_message

sample_event = discovery[0]
print(EXTRACTION_SYSTEM)
print("\n" + "=" * 80 + "\n")
print(build_user_message(sample_event)[:3000])

You compare an earnings release against what was expected before it.

You receive:
1. Facts from the earnings call, written after the release.
2. A research preview written BEFORE the release: consensus, guidance, and the issues the market is watching.

List every distinct way the reported results, guidance, or commentary differ from what the preview led investors to expect. Cover everything: headline numbers, guidance, segments, margins, operating metrics, capital allocation, one-off items, management tone, and anything the preview flagged as a key debate. Also cover surprises the preview did not anticipate at all.

Rules:
- One item per distinct surprise. Do not merge unrelated surprises; do not split one into many.
- Describe each surprise concretely in plain language. Do not label it with an abstract category; the categories will be derived later from many releases.
- Measure every surprise against the expectation, not against the prior year. Strong growth that matched consensus is not a surprise; put it under in_line.
- Use only the material provided. Do not use outside knowledge of this company or of how its stock traded.
- Do not predict the stock reaction.

================================================================================

Ticker: QMCO
Release time: 2026-08-10T21:00:00+00:00

Facts from the earnings call:
1. Q1 FY2027 revenue was $80.8 million, up 25.7% year-over-year and roughly 4% sequentially, exceeding guidance of $75 million (+/- $2 million).
2. GAAP gross margin reached 39.3%, up 360 basis points sequentially and nearly 400 basis points year-over-year, marking the highest level in five quarters.
3. Adjusted EBITDA was a positive $8 million, $5.5 million above the high end of guidance and up from a negative $6.5 million in the prior year quarter.
4. The company became debt-free after eliminating $144.8 million of term debt and convertible notes, using $56.8 million of $94.6 million net private placement proceeds to repay debt.
5. Cash, cash equivalents, and restricted cash rose to $54.6 million from $16.2 million at fiscal 2026 year-end, and interest expense is expected to be minimal going forward versus $21.6 million in fiscal 2026.
6. GAAP net loss was $155.3 million ($7.06 per share), driven by $157.7 million in one-time non-cash debt-related charges including a $129.7 million loss on convertible note fair value change.
7. Non-GAAP net income was $4 million ($0.18 per share), the first positive non-GAAP adjusted net income since 2023, versus a $14.5 million loss a year earlier.
8. Q2 FY2027 revenue guidance is approximately $82 million (+/- $2 million), representing ~31% year-over-year growth at the midpoint, but adjusted EBITDA is guided down to $6 million due to higher R&D hiring and sales commissions.
9. Growth was broad-based with Americas revenue up over 20% sequentially, APAC up over 50%, and service revenue up ~10%, alongside a significantly higher backlog (prior quarter was $45 million).
10. Tape drive supply constraints remain the primary limiter on revenue, with no inflection point seen as of August despite IBM's projected production increases in the back half of the year.

Research preview written BEFORE the release (expectations, not results):
# Quantum Corporation (QMCO) — Q1 FY2027 Earnings Preview

**Report date:** Monday, August 10, 2026, 4:05 p.m. ET (20:05 UTC) — after market close
**Conference call:** 5:00 p.m. ET, hosted by CEO Hugues Meyrath and CFO William White
**Quarter:** Fiscal Q1 2027, ended June 30, 2026
**Price (Aug 10, intraday):** $11.65, ‑3.2% | Mkt cap ~$459M | 52-wk range $4.19–$18.48 | Beta 3.0

> Methodological note: QMCO has only **two** covering analysts, so "consensus" is a two-point average and is unusually fragile. Every estimate below is sourced and dated, and stale (pre-guidance) figures are flagged. Published EPS estimates range from ($0.14) to ($0.24) depending on vintage.

> Date note: some third-party calendars list Aug 11 or Sep 10. The company's own release and the scheduled event confirm **Aug 10 after close**.

---

## 1. Consensus vs. Guidance

| Metric | Company guidance (Jun 25, 2026) | Consensus | Q4 FY26 actual | Q1 FY26 actual |
|---|---|---|---|---|
| Revenue | **$75.0M ± $2M** (+17% YoY) | $75.05M *

In [ ]:
result = extraction.extract_event(sample_event)
for s in result.surprises:
    print(f"[{s.direction}/{s.magnitude}/{s.expectation_source}] {s.description}")
print("\nIn line:", *result.in_line, sep="\n- ")

### Run on the discovery set

Start with a small `N` as a smoke test, then set `N = None` for all 500.

In [ ]:
N = None  # None for the whole discovery set

summary = extraction.run_extraction(
    discovery[:N] if N else discovery,
    model=extraction.DEFAULT_MODEL,
    effort=extraction.DEFAULT_EFFORT,
    workers=8,
)
summary

## 3. Look at the results

In [21]:
# Only the current discovery sample; the file may hold extractions from an earlier split.
discovery_ids = set(split["discovery"])
records = [r for r in extraction.load_extractions() if r["event_id"] in discovery_ids]
items = pd.DataFrame([
    {"event_id": r["event_id"], "ticker": r["ticker"], "car1": r["car1"], **s}
    for r in records
    for s in r["surprises"]
])
per_event = items.groupby("event_id").size()
print(f"{len(records)} events, {len(items)} surprise items, {per_event.mean():.1f} per event on average")
items.head()

500 events, 3895 surprise items, 7.8 per event on average

,event_id,ticker,car1,description,direction,magnitude,fact_evidence,expectation_evidence,expectation_source
0,ea_QMCO_Q1_2027,QMCO,0.649427,"QMCO reported adjusted EBITDA of $8 million, f...",positive,large,"“Adjusted EBITDA was a positive $8 million, $5...",“Adj. EBITDA: $1.5M ± $1M.”,preview
1,ea_QMCO_Q1_2027,QMCO,0.649427,"Instead of the expected non-GAAP loss, QMCO re...",positive,large,“Non-GAAP net income was $4 million ($0.18 per...,“Non-GAAP EPS: ($0.15) ± $0.10”; consensus was...,preview
2,ea_QMCO_Q1_2027,QMCO,0.649427,"Revenue came in at $80.8 million, above both t...",positive,moderate,“Q1 FY2027 revenue was $80.8 million … exceedi...,“Consensus sits exactly on the guidance midpoi...,preview
3,ea_QMCO_Q1_2027,QMCO,0.649427,"GAAP gross margin reached 39.3%, above the pre...",positive,moderate,"“GAAP gross margin reached 39.3%, up 360 basis...",The preview calculated “~38% gross margin” imp...,preview
4,ea_QMCO_Q1_2027,QMCO,0.649427,Q2 revenue guidance is approximately $82 milli...,positive,moderate,“Q2 FY2027 revenue guidance is approximately $...,The preview said “a Q2 guide below ~$78M puts ...,preview

In [22]:
items[["direction", "magnitude", "expectation_source"]].apply(pd.Series.value_counts).fillna(0).astype(int)

          direction  magnitude  expectation_source
call              0          0                  34
large             0        655                   0
mixed           437          0                   0
moderate          0       2424                   0
negative       1079          0                   0
none              0          0                 680
positive       2318          0                   0
preview           0          0                3181
small             0        816                   0
unclear          61          0                   0

In [23]:
# Rough check that the direction labels carry signal:
# net direction per event (positive minus negative items) vs. the realized return.
net = (
    items.assign(score=items["direction"].map({"positive": 1, "negative": -1}).fillna(0))
    .groupby("event_id")
    .agg(net_direction=("score", "sum"), car1=("car1", "first"))
)
# Spearman = Pearson on ranks; computed this way so it doesn't need scipy.
ranks = net[["net_direction", "car1"]].rank()
print("Spearman:", round(ranks["net_direction"].corr(ranks["car1"]), 3))
net.groupby("net_direction")["car1"].agg(["count", "mean", "median"])

Spearman: 0.465

               count      mean    median
net_direction
-9.0               1 -0.132534 -0.132534
-8.0               1 -0.254943 -0.254943
-6.0               3 -0.125514 -0.006329
-5.0               8 -0.060753 -0.145945
-4.0              11 -0.142393 -0.133860
-3.0              15 -0.081926 -0.052462
-2.0              24 -0.054421 -0.055611
-1.0              38 -0.053351 -0.046273
 0.0              40 -0.067787 -0.049265
 1.0              62 -0.027080 -0.021583
 2.0              47 -0.008203 -0.000885
 3.0              58  0.017107  0.006594
 4.0              48  0.081782  0.041635
 5.0              46  0.055212  0.034568
 6.0              32  0.049975  0.032950
 7.0              27  0.062912  0.040423
 8.0              19  0.122005  0.088010
 9.0               8  0.094618  0.060591
 10.0              5  0.102444  0.083806
 11.0              3  0.176169  0.215338
 12.0              3  0.046857  0.090846
 13.0              1  0.443818  0.443818

In [24]:
# Read the raw items for one event.
eid = records[0]["event_id"]
for s in items[items.event_id == eid].itertuples():
    print(f"[{s.direction}/{s.magnitude}/{s.expectation_source}] {s.description}\n")

[positive/large/preview] QMCO reported adjusted EBITDA of $8 million, far above the preview’s $1.5 million guidance midpoint and $5.5 million above the guidance range’s high end. This was a much stronger profitability result than expected.

[positive/large/preview] Instead of the expected non-GAAP loss, QMCO reported $4 million of non-GAAP net income, or $0.18 per share. That is a substantial reversal from the preview’s expected loss per share.

[positive/moderate/preview] Revenue came in at $80.8 million, above both the $75 million guidance midpoint and roughly $75 million consensus. The preview characterized revenue as a low-differentiation variable centered on guidance, so the size of the beat was better than expected.

[positive/moderate/preview] GAAP gross margin reached 39.3%, above the preview’s roughly 38% margin implied by guidance and above its 37% validation threshold. The preview identified margin recovery as the key debate, so this was a stronger recovery than its central expectation.

[positive/moderate/preview] Q2 revenue guidance is approximately $82 million, above the preview’s roughly $78 million reference point and the base-case range of $78–81 million. It meets the preview’s bull-case threshold rather than its base-case expectation.

[mixed/moderate/preview] The reported backlog was significantly higher than the prior quarter’s $45 million, rather than remaining roughly flat in the preview’s base case. That signals stronger demand, but alongside the continuing tape-drive constraint it also means orders are still not converting fully into shipments.

[negative/moderate/none] Despite the stronger Q2 revenue outlook, QMCO guided adjusted EBITDA down to $6 million, citing higher R&D hiring and sales commissions. The preview did not provide a Q2 EBITDA estimate or flag those costs, so this is an unanticipated near-term profitability headwind.

[mixed/large/none] QMCO reported a $155.3 million GAAP net loss, driven by $157.7 million in one-time non-cash debt-related charges, including a $129.7 million loss from the convertible-note fair-value change. The preview focused on non-GAAP EPS and did not flag these large GAAP charges, so the GAAP result was unexpectedly distorted by debt accounting.

## 4. Group items into dimensions (step 3)

The loop:

1. **Propose** a taxonomy (v1) from all items of 80 random discovery events, starting from a textbook seed list (`prompts.SEED_DIMENSIONS`).
2. **Assign** every item to one dimension or `other`. The model can only answer with a key from the current taxonomy.
3. **Review** the counts, the `other` bucket and a sample per dimension.
4. **Refine** to the next version and reassign. Stop when `other` is small (under ~5%) and a refinement makes few changes.
5. **Check stability** by proposing from a different sample and measuring agreement.

Each version is saved to `data/surprise/taxonomy/` (`taxonomy_<version>.json`, `assignments_<version>.jsonl`). Assignment resumes like extraction does.

Proposal and refinement use `grouping.PROPOSE_MODEL`; assignment uses the cheaper `grouping.ASSIGN_MODEL` in batches of 40 items (about 100 calls per full pass).

In [25]:
from suprise_dim import grouping

items_df = grouping.surprise_items(records)
print(f"{len(items_df)} items from {items_df['event_id'].nunique()} events")

3895 items from 500 events

### 4a. Propose v1

In [26]:
if grouping.taxonomy_path("v1").exists():
    tax_v1 = grouping.load_taxonomy("v1")
else:
    tax_v1 = grouping.propose_taxonomy(items_df, n_events=80, seed=0)
    grouping.save_taxonomy(tax_v1, "v1")

for d in tax_v1.dimensions:
    print(f"{d.key:32s} {d.definition}")
print("\nChanges vs. seed list:", *tax_v1.changes, sep="\n- ")

forward_guidance                 Surprises in management's forecasts, targets, or outlook for future financial results or recurring operating KPIs, including their timing, qualifications, reaffirmation, or withdrawal. Covers company-wide, segment, and product-level outlooks.
revenue                          Surprises in recognized revenue, sales, or their growth rates for any reporting period. Includes consolidated, segment, geographic, product, and channel revenue, whether reported, organic, pro forma, or constant-currency.
operating_profitability          Surprises in reported gross profit, operating income, EBITDA and related profit measures, margins, or accounting profitability ratios. Applies equally to consolidated and business-unit results.
bottom_line_earnings             Surprises in reported earnings per share, net income or loss, or total pretax bottom-line earnings. Includes GAAP, adjusted, continuing-operations, and comparable distributable or operating earnings per share.
operating_kpis                   Surprises in recurring measures of operating scale, demand, engagement, productivity, or performance that are not recognized revenue, accounting profit, or expense measures. Includes aggregate measures of contracted demand and forward revenue coverage.
cash_balance_sheet_liquidity     Surprises in reported cash generation, working capital, cash availability, debt balances, leverage, financial obligations, or liquidity constraints. Includes current assessments of funding runway and covenant status.
development_execution_regulatory Surprises in the status, timing, scope, or technical outcome of product development, commercial launches, operational projects, or company-specific regulatory processes. Includes implementation progress rather than recurring operating performance.
commercial_economics             Surprises in specific commercial relationships, customer or supplier commitments, pricing decisions, contract economics, monetization mechanisms, or the composition of business activity. Includes qualitative demand evidence tied to identifiable opportunities.
costs_expenses                   Surprises in reported recurring input costs, personnel costs, overhead, operating expenses, financing expenses, or cost efficiency. Includes cost-recovery shortfalls and expense ratios when the expense itself is focal.
capital_allocation               Surprises in decisions or completed actions governing the use of capital, including shareholder returns, capital expenditure, investment commitments, and cash debt repayment. Includes stated priorities among competing uses of funds.
financing_capital_structure      Surprises in obtaining, refinancing, restructuring, or converting financing and in the associated terms, dilution, security, or collateral. Includes identified grants, awards, or contingent funding sources, rather than ordinary customer payments.
strategy_corporate_events        Surprises in corporate scope, strategic priorities, M&A, divestitures, organizational design, leadership, or broad operating-model choices. Includes announced initiatives whose focal content is a change in how the business is organized or managed.
accounting_tax_special_items     Surprises specifically about accounting treatment, tax rates or credits, valuation adjustments, or separately identified exceptional gains, losses, charges, and settlements. Tax surprises belong here whether recurring or nonrecurring.
external_environment             Surprises in external market conditions, industry demand, benchmark prices, competitive or technological forces, broad public policy, or the size of an addressable opportunity. Includes management's newly quantified exposure or sensitivity to these external conditions.
disclosure_delivery              Surprises consisting of the absence, incompleteness, or unexpected provision of a specifically anticipated non-guidance disclosure. Use only when the disclosure gap or delivery itself is the focal surprise and no substantive result or event resolves it.

Changes vs. seed list:
- Retained forward guidance, with an explicit boundary between forecasts of results or recurring KPIs and announcements of transactions, launches, regulatory milestones, or capital-use decisions.
- Dropped segment/product-line performance as a separate dimension: reporting scope does not change the subject of a revenue, profit, expense, or KPI surprise.
- Retained separate bottom-line earnings, operating profitability, and expense dimensions because these are common, distinct focal surprises throughout the items.
- Generalized industry-specific KPIs to recurring operating and demand KPIs; placed accounting profitability ratios such as net interest margin and ROE under operating profitability.
- Added commercial economics to distinguish specific contracts, pricing, monetization, and business mix from aggregate KPI performance.
- Added development, execution, and regulatory milestones to cover trials, launches, operational projects, capacity-expansion initiatives, and company-specific regulatory proceedings across industries.
- Separated financing transactions and capital structure from financial-position outcomes and capital deployment, reflecting frequent issuance, conversion, refinancing, dilution, and collateral surprises.
- Expanded one-off items into accounting, taxes, and discrete special items so recurring tax-rate surprises also have a clear home.
- Added external environment for benchmark prices, industry conditions, broad policy, competitive forces, and addressable-market estimates.
- Replaced management tone and credibility with narrowly defined disclosure delivery; concrete forecasts, strategic choices, and regulatory interpretations are classified by subject rather than sentiment.
- Universal coding rule: classify the focal deviation, not its explanatory cause or contextual benchmark. If an item contains multiple independently surprising claims from different dimensions, assign the first independently surprising new claim in textual order; ignore preceding descriptions of the preview's expectations.
- Apply disclosure delivery only when no substantive result or event supplies the surprise; absent financial guidance always belongs to forward guidance. Items with no qualifying subject remain unassigned for review rather than entering a catch-all.

### 4b. Assign every item under v1

Try `items_df.head(200)` first to check the output, then run on all items.

In [28]:
grouping.assign_items(items_df, tax_v1, "v1")
asg_v1 = grouping.load_assignments("v1")
print(f"{len(asg_v1)}/{len(items_df)} items assigned")
asg_v1["dimension"].value_counts().to_frame("items").assign(share=lambda t: (t["items"] / t["items"].sum()).round(3))

Assigning 3695 items in 93 batches (200 already done) with gpt-6-luna...
[1/93] 40/40 assigned
[2/93] 40/40 assigned
[3/93] 40/40 assigned
[4/93] 40/40 assigned
[5/93] 40/40 assigned
[6/93] 40/40 assigned
[7/93] 40/40 assigned
[8/93] 40/40 assigned
[9/93] 40/40 assigned
[10/93] 40/40 assigned
[11/93] 40/40 assigned
[12/93] 40/40 assigned
[13/93] 40/40 assigned
[14/93] 40/40 assigned
[15/93] 40/40 assigned
[16/93] 40/40 assigned
[17/93] 40/40 assigned
[18/93] 40/40 assigned
[19/93] 40/40 assigned
[20/93] 40/40 assigned
[21/93] 40/40 assigned
[22/93] 40/40 assigned
[23/93] 40/40 assigned
[24/93] 40/40 assigned
[25/93] 40/40 assigned
[26/93] 40/40 assigned
[27/93] 40/40 assigned
[28/93] 40/40 assigned
[29/93] 40/40 assigned
[30/93] 40/40 assigned
[31/93] 40/40 assigned
[32/93] 40/40 assigned
[33/93] 40/40 assigned
[34/93] 40/40 assigned
[35/93] 40/40 assigned
[36/93] 40/40 assigned
[37/93] 40/40 assigned
[38/93] 40/40 assigned
[39/93] 40/40 assigned
[40/93] 40/40 assigned
[41/93] 40/40 assigned
[42/93] 40/40 assigned
[43/93] 40/40 assigned
[44/93] 40/40 assigned
[45/93] 40/40 assigned
[46/93] 40/40 assigned
[47/93] 40/40 assigned
[48/93] 40/40 assigned
[49/93] 40/40 assigned
[50/93] 40/40 assigned
[51/93] 40/40 assigned
[52/93] 40/40 assigned
[53/93] 40/40 assigned
[54/93] 40/40 assigned
[55/93] 40/40 assigned
[56/93] 40/40 assigned
[57/93] 40/40 assigned
[58/93] 40/40 assigned
[59/93] 40/40 assigned
[60/93] 40/40 assigned
[61/93] 40/40 assigned
[62/93] 40/40 assigned
[63/93] 40/40 assigned
[64/93] 40/40 assigned
[65/93] 40/40 assigned
[66/93] 40/40 assigned
[67/93] 40/40 assigned
[68/93] 40/40 assigned
[69/93] 40/40 assigned
[70/93] 40/40 assigned
[71/93] 40/40 assigned
[72/93] 40/40 assigned
[73/93] 40/40 assigned
[74/93] 40/40 assigned
[75/93] 40/40 assigned
[76/93] 40/40 assigned
[77/93] 40/40 assigned
[78/93] 40/40 assigned
[79/93] 40/40 assigned
[80/93] 40/40 assigned
[81/93] 40/40 assigned
[82/93] 40/40 assigned
[83/93] 40/40 assigned
[84/93] 40/40 assigned
[85/93] 40/40 assigned
[86/93] 40/40 assigned
[87/93] 40/40 assigned
[88/93] 40/40 assigned
[89/93] 15/15 assigned
[90/93] 40/40 assigned
[91/93] 39/40 assigned
[92/93] 40/40 assigned
[93/93] 40/40 assigned
Done. 3694 written, 1 missing, 0 batches failed; call again to retry.
3894/3895 items assigned

                                  items  share
dimension
forward_guidance                    660  0.169
revenue                             584  0.150
operating_kpis                      518  0.133
operating_profitability             460  0.118
bottom_line_earnings                266  0.068
cash_balance_sheet_liquidity        244  0.063
development_execution_regulatory    239  0.061
commercial_economics                232  0.060
capital_allocation                  161  0.041
costs_expenses                      148  0.038
strategy_corporate_events           123  0.032
accounting_tax_special_items         89  0.023
external_environment                 85  0.022
financing_capital_structure          66  0.017
disclosure_delivery                  18  0.005
other                                 1  0.000

### 4c. Review

In [29]:
def review(asg, n_other=20, n_per_dim=3, seed=0):
    merged = items_df.merge(asg, on="item_id")
    other = merged[merged["dimension"] == grouping.OTHER]
    print(f"other: {len(other)} items ({len(other) / len(merged):.1%})\n")
    for text in other.sample(min(n_other, len(other)), random_state=seed)["description"]:
        print("-", text)
    for dim, rows in merged[merged["dimension"] != grouping.OTHER].groupby("dimension"):
        print(f"\n### {dim} ({len(rows)})")
        for text in rows.sample(min(n_per_dim, len(rows)), random_state=seed)["description"]:
            print("-", text)

review(asg_v1)

other: 1 items (0.0%)

- Duke reported $5 billion of economic-development investment and support for more than 9,000 jobs in the first half of 2026, an unanticipated positive operating and community-development update.

### accounting_tax_special_items (89)
- Owlet received about $4 million in tariff refunds, lifting Q2 gross margin and adjusted EBITDA: reported gross margin was 64.4% and adjusted EBITDA was $6.7 million including the refund, versus 54% and $2.9 million excluding it. The preview did not anticipate this one-time benefit.
- The tariff-refund benefit was much more concrete and material than the preview’s base case allowed for: Fortune Brands recognized $122 million gross, with $81 million flowing to operating income. It added 700 basis points to consolidated margin and $0.52 to quarterly EPS, helping lift reported operating margin to 20.4% versus the preview’s 13.0%–13.5% model.
- PRA increased European ERC by $349 million after a portfolio review, an unanticipated upward revision that management said reflects repeated overperformance. It expects about $260 million of additional portfolio income over the remaining cash curves, although the near-term annualized contribution is about $25 million and the 2026 net income effect is nominal.

### bottom_line_earnings (266)
- Q2 operating loss and EPS were at or better than the favorable ends of their ranges: non-GAAP operating loss was $28.8 million, slightly better than the $29–32 million guide, and EPS loss was $0.13 versus consensus loss of $0.14. The preview generally expected results around the guide and consensus.
- FY2026 EPS was $1.00 versus the preview’s $0.94 estimate, a modest beat. Full-year revenue of $1.518 billion was close to the preview’s $1.51 billion estimate.
- UHAL.B earned $0.63 per share, below the preview’s roughly $0.80 base estimate and down from $0.73 a year earlier, rather than delivering the preview’s expected year-over-year growth. The preview cautioned that reported EPS consensus was unreliable, so the comparison is to its own estimate.

### capital_allocation (161)
- Devon completed its full $1.25 billion 2026 debt-reduction target by July, earlier than the preview’s expectation of completing that amount over the year. The amount was expected; the early completion was the positive difference.
- Share repurchases accelerated from the $23.1 million bought back in Q1 to $41 million in Q2, exceeding the preview’s open question about whether buybacks would accelerate.
- Buybacks were $641 million, below the preview’s $700 million–$1.0 billion base-case quarterly range and well below its $1.0–$1.5 billion acceleration scenario. Total shareholder returns were higher at $904 million after including dividends, but the repurchase pace itself fell short of the preview’s baseline.

### cash_balance_sheet_liquidity (244)
- Debbie’s reported principal recovery had risen to $58 million, far above the $20.8 million cumulative recovery cited through Q1, and AFC had a binding term sheet to sell two assets for $12.5 million with a $2 million hard deposit. This is substantially more recovery and a firmer resolution step than the preview highlighted.
- Net debt fell to $767 million, $36 million below the preview’s roughly $803 million figure, and management reported a $58 million year-to-date reduction. That is a better debt balance than the preview’s covenant discussion assumed, despite the weak EBITDA.
- Management said it does not expect to need additional equity for near-term commitments, easing the dilution concern raised in the preview. Unrestricted liquidity was also $870 million versus $715 million at Q1, although total debt had risen above $6 billion.

### commercial_economics (232)
- Q3 promotional activity created a pricing headwind, a pressure the preview did not specifically flag. Management said pricing should be neutral to slightly positive in Q4 and cautioned investors not to extrapolate Q3 pricing trends.
- Cobrand card remuneration grew 24% year over year, and management set a goal of doubling its share of revenue from 5% to 10%. The preview did not flag this revenue stream or the stated growth target.
- The UBS/Credit Suisse client attrition creates an additional 2026 Capital Markets headwind that the preview did not identify: it is expected to reduce segment revenue growth by about one percentage point, concentrated in trading and asset services.

### costs_expenses (148)
- Management reported substantial self-help savings, including more than $20 million of indirect-spend savings year-to-date and a target above $75 million this year, with over $100 million targeted in 2027. The preview flagged initiatives but did not set expectations for these savings amounts.
- Instead of the preview’s concern about possible cost inflation, production expenses per BOE were down year over year and normalized AFE costs were also lower than the 2025 average. The reported reductions were modest but favorable against the cost-risk framing.
- SVV reported a larger annualized interest-expense reduction than the preview’s modeled quarterly tailwind would suggest. The preview expected about $2 million per quarter from the prior refinancing; the call cited approximately $20 million of annualized savings from refinancing and repricing over the past year.

### development_execution_regulatory (239)
- The LAKE sample-size re-estimation could increase the trial by as much as 50%, a potential expansion the preview did not quantify. Management characterized any increase as routine rather than a negative signal, tempering the concern but not removing the possibility of a larger trial.
- The call added two Q4 pipeline events beyond the preview’s named IPF and frontline chronic GVHD readouts: a NUP98 relapsed/refractory publication and updated frontline AML trial data. These broadened the set of anticipated fourth-quarter updates, though no results were reported.
- ECA LNG Phase 1 suffered equipment damage and substantial completion moved to Q4 2026, rather than the preview’s commissioning-ramp outlook after noting that the first cargo had already been exported. The call said this does not prevent the SI Partners transaction from closing.

### disclosure_delivery (18)
- Management said it expects a decision soon on the strategic-alternatives review, a more specific near-term signal than simply saying the process is ongoing. However, it did not announce a transaction or a defined timetable, which fell short of the preview’s hoped-for evidence.
- Although the full-year revenue range was reaffirmed, the supplied call facts do not provide the quantified PO values, backlog, or shipment schedules that the preview identified as important proof for the required second-half ramp. The new defense-order descriptions add some detail, but do not quantify that revenue path.
- Management described a potentially presidential-cycle-sized midterm political year, but the reported update did not provide the quantified Q3/Q4 political bookings or pacing the preview identified as needed to support the H2 ramp. The outlook therefore remained more aspirational than the concrete de-risking detail the preview sought.

### external_environment (85)
- Management made a strong valuation-disconnect argument that the preview had not anticipated, putting its estimated asset value well above enterprise value and emphasizing NOG’s share-price lag versus peers.
- SVOD ad pricing faced pressure from rising streaming supply, a negative advertising detail not anticipated in the preview.
- Category growth weakened more than the preview’s roughly 2.5% growth assumption: North American weighted category growth slowed to 1.9%, while global trailing-12-month growth slipped to about 2%. Management also cited increasing pressure on lower-income consumers.

### financing_capital_structure (66)
- The call put a potential value on the CEPI collaboration that the preview had not quantified: Dyadic is eligible for up to approximately $2.4 million. The amount is an eligibility ceiling, not a committed payment.
- Palladyne said it had submitted proposals to more than 20 Department of War funding programs with several hundred million dollars of aggregate initial potential value, an additional pipeline development not anticipated in the preview. These were proposals, not awards.
- The preview framed Sandersville’s roughly $2 billion buildout as a major funding gap and wanted an explicit answer on equity issuance. Management said the project’s equity portion is fully funded, no equity raises are planned for the project, and the investment-grade tenant supports favorable-rate financing without credit wrappers or equity backstops—meaningfully more reassuring, although no completed financing facility was reported.

### forward_guidance (660)
- Management said annual EPS growth is expected to exceed 8% beginning in 2028 through 2030. That is more specific and stronger than the preview’s 6–8%+ long-term growth framing and its 7.1% FY2027 growth estimate.
- The company raised full-year revenue growth guidance from high single digits to high single digits/low double digits. That is an upward revision beyond the previously affirmed high-single-digit outlook, though it is consistent with the preview’s upside scenario.
- Management gave the new audio ad-tech product a roughly $12 million annual run-rate target by fiscal year-end, a concrete target not anticipated in the preview. The preview mentioned VAUDIO only as a possible incremental catalyst.

### operating_kpis (518)
- Jet-engine revenue grew 13% year over year, with high-teens full-year growth expected, and ATI reported lead times reaching 20 months for premium titanium and over 24 months for isothermal forgings. Those lead times extend well beyond the preview’s general expectation of one-year-plus lead times for differentiated materials.
- GMV reached $1.3 billion, ahead of the preview’s roughly $1.25 billion base case and its expected 35% growth. It also set a new record, surpassing the prior Q4 holiday-season peak.
- Utilization slipped to 85% from 85.8% in Q1, rather than moving back toward the roughly 88% level the preview described as the cleanest bullish signal. The average lease rate did edge up, from 1.0% to 1.03%, but utilization remained weaker.

### operating_profitability (460)
- Despite revenue growth, adjusted EBITDA was flat as reported, rather than following the preview’s more optimistic setup of results trending toward the upper half of the full-year EBITDA range. Excluding asset-sale gains, EBITDA grew 7%, as the prior-year Beaumont gain was much larger than this year’s.
- The preview framed LBRDK as having “no standalone revenue” and said GCI was in discontinued operations, but the reported facts included $261 million of Q2 revenue and $96 million of adjusted OIBDA, down 11% year over year. The operating results were therefore much more substantive—and weaker on OIBDA—than the preview’s information-free-print framing suggested.
- Q3 adjusted EBITDA was $13.3 million, well below the preview’s roughly $15.4 million model, and its 25% margin fell short of the roughly 27–28% run rate the preview said was needed. The expected margin step-up had not yet appeared in the quarter.

### revenue (584)
- Revenue slightly exceeded the $63.55 million consensus, and the year-over-year increase was stronger than the preview’s expected 6.8%. The beat was modest, but it confirmed the expected return to year-over-year growth.
- Q2 revenue was $214 million, above the roughly $211–212 million implied by consensus and management’s prior “about 14%” growth outlook. The resulting 15% year-over-year growth was a modest beat.
- Energy Storage revenue reached $42.8 million, far exceeding the preview’s implied Q2 range of about $17–22 million, and its 56.2% gross margin was above the preview’s stated 35–40% full-year guide. The preview specifically identified a Q2 margin above 50% as upside.

### strategy_corporate_events (123)
- BuzzFeed said it aims to become a free streaming service and a “super app,” a specific strategic ambition not laid out in the preview’s discussion of Allen’s plans.
- The reported Celero combination places Deluxe among the top 10 nonbank merchant acquirers, a positioning milestone not identified in the preview’s description of the deal’s expected scale.
- Management said the 136 company-owned restaurants are tracking near breakeven EBITDA, with AUVs in the low $2 millions versus about $3 million for the system, and is beginning to consider refranchising them. That raises a portfolio-quality and refranchising question beyond the preview’s stated roughly three-year timeline for refranchising acquired units.

### 4c-2. Reliability of the assignment

Reassign 400 random items under the same taxonomy, in shuffled batches (the original pass batched items event by event), and compare labels item by item. The rerun is saved as `assignments_v1_rerun_s0.jsonl`, about 10 calls.

- **agreement**: share of items given the same dimension both times.
- **kappa**: agreement beyond chance; roughly, above 0.8 is strong, 0.6–0.8 is acceptable, below 0.6 means the boundaries are too fuzzy for the labels to be trusted.
- **per_dimension**: how often items of each v1 dimension keep their label. Low values point to the boundaries the refinement should fix.
- **confusions**: the most common pairs of dimensions the model switches between.

Pass `model=...` to compare a different assigner, or a new `seed` for another sample.

In [30]:
rel = grouping.reliability_check(items_df, tax_v1, "v1", n_items=400, seed=0)
print(f"{rel['n']} items: agreement {rel['agreement']:.1%}, Cohen's kappa {rel['kappa']:.3f}")
display(rel["per_dimension"].round(2))
rel["confusions"].head(15)

Assigning 400 items in 10 batches (0 already done) with gpt-6-luna...
[1/10] 40/40 assigned
[2/10] 40/40 assigned
[3/10] 40/40 assigned
[4/10] 40/40 assigned
[5/10] 40/40 assigned
[6/10] 40/40 assigned
[7/10] 40/40 assigned
[8/10] 40/40 assigned
[9/10] 40/40 assigned
[10/10] 40/40 assigned
Done. 400 written, 0 missing, 0 batches failed; call again to retry.
400 items: agreement 90.8%, Cohen's kappa 0.896

                                  items  agreement
dimension_a
forward_guidance                     65       0.89
revenue                              64       0.95
operating_kpis                       62       0.97
bottom_line_earnings                 36       0.92
operating_profitability              34       0.97
commercial_economics                 27       0.85
cash_balance_sheet_liquidity         24       1.00
development_execution_regulatory     24       0.79
capital_allocation                   16       0.81
costs_expenses                       15       0.87
external_environment                 10       0.90
strategy_corporate_events            10       0.80
accounting_tax_special_items          8       0.62
financing_capital_structure           3       0.67
disclosure_delivery                   2       1.00

                         dimension_a                   dimension_b  items
0               bottom_line_earnings       operating_profitability      3
1                   forward_guidance                operating_kpis      3
2                            revenue                operating_kpis      2
3       accounting_tax_special_items          bottom_line_earnings      1
4   development_execution_regulatory     strategy_corporate_events      1
5          strategy_corporate_events          external_environment      1
6                            revenue          commercial_economics      1
7            operating_profitability  accounting_tax_special_items      1
8                     operating_kpis                       revenue      1
9                     operating_kpis       operating_profitability      1
10                  forward_guidance       operating_profitability      1
11                  forward_guidance          external_environment      1
12                  forward_guidance          commercial_economics      1
13                  forward_guidance            capital_allocation      1
14       financing_capital_structure            capital_allocation      1

### 4d. Refine and reassign

Set `PREV` / `NEXT` and rerun this cell for each round (v1 → v2 → v3 …). `agreement` is the normalized mutual information between the two versions' assignments: close to 1 means the refinement barely changed how items are grouped.

In [31]:
PREV, NEXT = "v1", "v2"

tax_prev, asg_prev = grouping.load_taxonomy(PREV), grouping.load_assignments(PREV)
if grouping.taxonomy_path(NEXT).exists():
    tax_next = grouping.load_taxonomy(NEXT)
else:
    tax_next = grouping.refine_taxonomy(tax_prev, items_df, asg_prev)
    grouping.save_taxonomy(tax_next, NEXT)
print(f"{PREV} -> {NEXT} changes:", *tax_next.changes, sep="\n- ")

grouping.assign_items(items_df, tax_next, NEXT)
asg_next = grouping.load_assignments(NEXT)

nmi, table = grouping.agreement(asg_prev, asg_next)
print(f"\nAgreement {PREV} vs {NEXT}: NMI = {nmi:.3f}")
print(f"other: {PREV} {(asg_prev['dimension'] == grouping.OTHER).mean():.1%} -> {NEXT} {(asg_next['dimension'] == grouping.OTHER).mean():.1%}")
table

v1 -> v2 changes:
- Reordered dimensions by assigned frequency, retaining counts only as ordering evidence rather than estimating reassigned totals.
- Extended operating_kpis to cover recurring company-supported economic-development investment and jobs, absorbing the lone other item; distinguished facilitated activity from the company's own capital deployment.
- Tightened operating_kpis and revenue boundaries: recognized product or brand sales belong to revenue, sales penetration and business mix to commercial_economics, and aggregate awards to operating_kpis.
- Clarified forward_guidance coverage of future savings, business-mix targets, and quantified financial contributions, while distinguishing current funded runway from future financial targets.
- Clarified cash_balance_sheet_liquidity coverage of current funding sufficiency, principal recoveries, and early leverage-target attainment; separated balances from repayment actions and asset-sale agreements.
- Tightened development_execution_regulatory to exclude aggregate orders, including new-technology orders with future delivery dates.
- Tightened commercial_economics to exclude aggregate awarded-but-unsigned contracts, recognized remuneration revenue, and focal financial forecasts; clarified sales-penetration and sales-representation coverage.
- Tightened capital_allocation to distinguish repayment decisions from resulting leverage levels, negotiated amendment obligations, and facilitated third-party investment.
- Clarified costs_expenses coverage of savings already realized or secured by completed actions, versus future savings targets, restructuring programs, and focal refinancing or lease arrangements.
- Clarified strategy_corporate_events coverage of substantive strategic-review status and timing updates, addressing an item assigned to disclosure_delivery despite an actual process update.
- Separated reporting-practice changes from disclosure-delivery gaps and incorporated them into the expanded accounting_tax_special_items dimension, avoiding a small standalone reporting category.
- Tightened accounting_tax_special_items to keep focal EPS comparisons in bottom_line_earnings when special items merely explain the result.
- Extended external_environment to cover non-accounting market-relative valuation assessments; tightened exclusions for company revenue and operating-metric results explained by external conditions.
- Clarified financing_capital_structure coverage of identified proposals, contingent funding ceilings, refinancing plans, amendments, and contractual rate changes; excluded generic non-dilutive revenue aspirations, current funding sufficiency, and focal expense savings.
- Tightened disclosure_delivery to exclude substantive strategic updates and announced reporting-policy changes, retaining it for concrete unresolved disclosure gaps.
Assigning 3895 items in 98 batches (0 already done) with gpt-6-luna...
[1/98] 40/40 assigned
[2/98] 40/40 assigned
[3/98] 40/40 assigned
[4/98] 40/40 assigned
[5/98] 40/40 assigned
[6/98] 40/40 assigned
[7/98] 40/40 assigned
[8/98] 40/40 assigned
[9/98] 40/40 assigned
[10/98] 40/40 assigned
[11/98] 40/40 assigned
[12/98] 40/40 assigned
[13/98] 40/40 assigned
[14/98] 40/40 assigned
[15/98] 40/40 assigned
[16/98] 40/40 assigned
[17/98] 40/40 assigned
[18/98] 40/40 assigned
[19/98] 40/40 assigned
[20/98] 40/40 assigned
[21/98] 40/40 assigned
[22/98] 40/40 assigned
[23/98] 40/40 assigned
[24/98] 40/40 assigned
[25/98] 40/40 assigned
[26/98] 40/40 assigned
[27/98] 40/40 assigned
[28/98] 40/40 assigned
[29/98] 40/40 assigned
[30/98] 40/40 assigned
[31/98] 40/40 assigned
[32/98] 40/40 assigned
[33/98] 40/40 assigned
[34/98] 40/40 assigned
[35/98] 40/40 assigned
[36/98] 40/40 assigned
[37/98] 40/40 assigned
[38/98] 40/40 assigned
[39/98] 40/40 assigned
[40/98] 40/40 assigned
[41/98] 40/40 assigned
[42/98] 40/40 assigned
[43/98] 40/40 assigned
[44/98] 40/40 assigned
[45/98] 40/40 assigned
[46/98] 40/40 assigned
[47/98] 40/40 assigned
[48/98] 40/40 assigned
[49/98] 40/40 assigned
[50/98] 40/40 assigned
[51/98] 40/40 assigned
[52/98] 40/40 assigned
[53/98] 40/40 assigned
[54/98] 40/40 assigned
[55/98] 40/40 assigned
[56/98] 40/40 assigned
[57/98] 40/40 assigned
[58/98] 40/40 assigned
[59/98] 40/40 assigned
[60/98] 40/40 assigned
[61/98] 40/40 assigned
[62/98] 40/40 assigned
[63/98] 40/40 assigned
[64/98] 40/40 assigned
[65/98] 40/40 assigned
[66/98] 40/40 assigned
[67/98] 40/40 assigned
[68/98] 40/40 assigned
[69/98] 40/40 assigned
[70/98] 40/40 assigned
[71/98] 40/40 assigned
[72/98] 40/40 assigned
[73/98] 40/40 assigned
[74/98] 40/40 assigned
[75/98] 40/40 assigned
[76/98] 40/40 assigned
[77/98] 40/40 assigned
[78/98] 40/40 assigned
[79/98] 40/40 assigned
[80/98] 40/40 assigned
[81/98] 40/40 assigned
[82/98] 40/40 assigned
[83/98] 40/40 assigned
[84/98] 40/40 assigned
[85/98] 40/40 assigned
[86/98] 40/40 assigned
[87/98] 40/40 assigned
[88/98] 40/40 assigned
[89/98] 40/40 assigned
[90/98] 40/40 assigned
[91/98] 40/40 assigned
[92/98] 40/40 assigned
[93/98] 40/40 assigned
[94/98] 40/40 assigned
[95/98] 15/15 assigned
[96/98] 40/40 assigned
[97/98] 40/40 assigned
[98/98] 40/40 assigned
Done. 3895 written, 0 missing, 0 batches failed; call again to retry.

Agreement v1 vs v2: NMI = 0.832
other: v1 0.0% -> v2 0.0%

dimension_b,accounting_tax_special_items,bottom_line_earnings,capital_allocation,cash_balance_sheet_liquidity,commercial_economics,costs_expenses,development_execution_regulatory,disclosure_delivery,external_environment,financing_capital_structure,forward_guidance,operating_kpis,operating_profitability,other,revenue,strategy_corporate_events
dimension_a,,,,,,,,,,,,,,,,
accounting_tax_special_items,80,4,0,2,0,1,0,0,1,0,0,1,0,0,0,0
bottom_line_earnings,0,259,0,0,0,0,0,0,0,0,1,0,3,0,3,0
capital_allocation,0,0,139,1,2,1,0,0,0,1,6,2,0,0,0,9
cash_balance_sheet_liquidity,1,0,1,238,0,0,0,0,0,1,0,2,0,1,0,0
commercial_economics,0,0,2,0,179,0,4,0,3,0,13,28,0,0,2,1
costs_expenses,1,0,1,0,1,136,0,0,2,0,6,0,1,0,0,0
development_execution_regulatory,1,0,0,0,4,1,200,1,4,2,6,12,0,0,3,5
disclosure_delivery,2,0,0,1,0,0,0,14,0,0,0,0,0,0,0,1
external_environment,0,0,0,0,2,1,0,0,70,0,7,4,0,0,1,0
financing_capital_structure,0,0,1,2,0,0,1,0,0,62,0,0,0,0,0,0
forward_guidance,1,0,3,7,3,3,2,0,1,1,632,2,1,0,4,0
operating_kpis,1,1,1,1,22,1,0,0,2,0,3,456,4,0,25,1
operating_profitability,4,5,0,2,3,2,0,0,0,0,1,5,436,0,2,0
other,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
revenue,1,0,0,0,2,0,1,0,0,0,4,8,4,0,564,0
strategy_corporate_events,0,0,4,0,2,1,0,1,1,0,6,2,0,0,1,105

In [32]:
review(asg_next)

other: 1 items (0.0%)

- Book value per share was $36, below the preview’s approximate $37 expectation. The company still reported 8.5% year-over-year growth, but the reported level was lower than the preview anticipated.

### accounting_tax_special_items (92)
- The quarter included about $100 million of net positive mark-to-market and timing impacts, but management said the first half still had a carried net negative position that would mostly reverse in Q3. That makes the Q2 timing benefit real but less complete or earlier than the preview’s discussion of a Q2 reversal might have led investors to expect.
- The quarter included $8.6 million of 45Z credits, slightly above the preview’s expected $5–8 million contribution. The preview’s range was close, so the excess was modest rather than a major departure.
- A $9.9 million unrealized gain on a minority equity investment was recorded in other income, an unanticipated gain that increased reported income but was not a recurring operating result.

### bottom_line_earnings (269)
- Adjusted net income was $0.48 per share, below the preview’s $0.51–$0.52 consensus and its $0.53 model estimate. The shortfall was also larger against the preview’s estimated $0.54–$0.56 whisper range.
- Non-GAAP EPS reached $0.71, above both the preview’s $0.69 consensus and the $0.68–$0.70 guided range. That was a stronger result than the preview’s base case of $0.69–$0.70.
- Adjusted diluted EPS was $1.18 versus the preview’s $0.97–$0.98 consensus range, a much larger beat than expected. The call also said results benefited from a one-time executive compensation clawback tied to an earlier restatement, qualifying the strength of the reported result.

### capital_allocation (152)
- Management authorized repurchases of up to 1.5 million shares, a concrete expansion of buyback capacity beyond the preview’s reference to only 90,000 shares repurchased in Q4 and its discussion of possible buyback acceleration.
- The preview did not anticipate a new shareholder distribution policy, but Liberty Capital announced a quarterly dividend of about $15 million, or $60 million annually, beginning in December 2025. Management expects it to use about half of next year’s free cash flow.
- The company repurchased about $100 million of stock in Q2, a sharp acceleration from the $24.1 million repurchased in Q1 and more than the preview’s general expectation of an accelerated pace.

### cash_balance_sheet_liquidity (255)
- Net leverage was 2.5x, better than the preview’s estimate of just under 3.0x, leaving more acquisition capacity than expected. The preview had anticipated additional M&A in 2026, which management reiterated.
- Free-cash-flow conversion of 111% was in line with the preview’s full-year 110–115% expectation, but the reported 220-basis-point improvement in operating working capital and 37% rise in free cash flow were additional favorable cash-generation details not specifically anticipated.
- Quarter-end cash including restricted cash reached $15.7 million, above the preview’s estimated $12–13 million pro forma balance, and the company repaid senior promissory notes and original issue discount notes. The cash comparison is approximate because the reported figure includes restricted cash.

### commercial_economics (220)
- SpaceMD agreed to buy an entire SpaceX Starfall spacecraft, intended to launch in 2028 and carry up to 32 PIL-BOXes. This commercial opportunity was not anticipated in the preview.
- The $750,000 ticket tranche was oversubscribed, adding more than $50 million to expected future spaceflight revenue, and management plans to offer a new tranche at higher prices. This is stronger evidence of demand and pricing power than the preview’s watchlist of whether deposits and reservations would rise.
- The preview did not anticipate a specific DOCSIS 4.0 customer win. Mediacom selected AOI as its primary vendor for DOCSIS 4.0 upgrades, a new positive indication for the CATV business.

### costs_expenses (147)
- Input-cost inflation was described as leveling off, whereas the preview expected it to be accelerating into Q1. The Q2 gross-margin outlook still includes a roughly 200-basis-point year-over-year headwind, so the more favorable news is the change in inflation trend rather than the disappearance of cost pressure.
- Management quantified a manufacturing ramp-up drag of about $0.03 per share in Q2 and expects $0.03–$0.04 per share in Q3. That is a more concrete near-term earnings cost than the preview’s characterization of the 2026 EPS impact as minimal, though the expected mid-2027 margin benefits remain on the preview’s timeline.
- SG&A rose 31% to $27.7M rather than flattening as the preview’s operating-leverage bull case anticipated. Management attributed much of the increase to a $5.3M one-time, non-recurring sales milestone, which limits how much of the increase appears ongoing.

### development_execution_regulatory (208)
- Management emphasized Vepinu’s differentiated profile in second-line ESR1-mutated breast cancer, citing a strong PFS treatment effect, higher response rates, and improved clinical benefit rates. The preview focused on launch readiness and did not flag this efficacy positioning as a key expectation.
- Virgin Galactic had been expected to begin its first commercial spaceflight in Q4 2026, but now says the first flight is delayed until February 2027. The delay was attributed to modest extensions across hundreds of installation tasks rather than one specific issue.
- The call disclosed a new construction deal at New York-New York with MGM, expected to start in 2–3 months and open early next year. The preview highlighted the America relaunch as Ark’s only organic growth catalyst and did not anticipate this project.

### disclosure_delivery (16)
- The call put meaningful revenue contribution from desktop AI PCs mainly in late 2027 and beyond, rather than providing near-term commercial metrics for the AI-compute opportunity. The stated $22 billion market target gives market context, but leaves the preview’s request for CORSAIR PRO pipeline, backlog, or bookings figures unanswered.
- The preview focused on ALTITUDE-AD’s timing and endpoints, but did not flag uncertainty over how the two doses would be judged. Management declined to say whether each dose is independently powered against placebo or disclose the powering framework, leaving investors without clarity on what would count as a positive result.
- Management described a potentially presidential-cycle-sized midterm political year, but the reported update did not provide the quantified Q3/Q4 political bookings or pacing the preview identified as needed to support the H2 ramp. The outlook therefore remained more aspirational than the concrete de-risking detail the preview sought.

### external_environment (84)
- The company raised its 2027 serviceable addressable market estimate to approximately $15 billion, with Data Center and I&D each representing about $6 billion. The preview did not flag a higher market-size estimate.
- Management put numbers on the potential U.S. market—about 20 million adults with uncontrolled or resistant hypertension—and the focused prescriber audience of roughly 50,000 physicians. The preview described the targeted prescribing segment but did not provide these market or physician counts.
- The preview mentioned wildfire season as a watch item but did not anticipate a Spokane-area event that left about 7,300 electric and 5,300 gas customers without service. A key transmission line has been restored and reduced the risk of capacity-related outages, though additional line and distribution damage still needs assessment.

### financing_capital_structure (67)
- MARA disclosed new $600 million Bitcoin-backed credit facilities, with a 7.56% weighted average borrowing cost and 54% of its Bitcoin holdings pledged as collateral. The preview focused on liquidity, debt, Bitcoin sales, and dilution but did not anticipate this borrowing and collateral arrangement.
- Ardelyx drew $50 million from its SLR arrangement, a financing step not identified in the preview, which had highlighted the cash balance and undrawn facility. The draw supported a higher reported cash balance, but also means more borrowing rather than an improvement funded solely by operations.
- The company disclosed a $20 million equity line of credit that had not been announced before the release. It provides a potential liquidity source, although it had not yet been drawn.

### forward_guidance (685)
- Cummins raised its FY2026 revenue-growth outlook to 10%–13% from 8%–11%, rather than merely narrowing the range toward its upper half as the preview’s base case anticipated. It also increased the midpoint of EBITDA-margin guidance to 18.25%.
- Management gave a FY27 revenue outlook but no FY27 gross-margin outlook, leaving unanswered the margin question the preview identified as the central event risk. Q1 gross-margin guidance of 10.4%–10.8% points to a normalized near-term margin, but does not provide an annual FY27 margin assumption.
- Engineered Materials was expected to be down year over year, with previewed adjusted EBIT of $190–$210 million versus $214 million a year earlier. Management instead expects adjusted EBIT to grow at double-digit rates, closer to 15%, despite inventory absorption, Micromax divestiture, and lower equity earnings.

### operating_kpis (523)
- Basket size rose 3.1%, a sharper increase than the 1.6% growth reported for Q2 and the preview’s expectation of a basket-led comp without an increase of this size. This strength was not enough to offset the worse-than-expected transaction decline.
- AIHESO demand was much stronger than the preview’s expectation of a somewhat muted quarter: units reached a record and rose 44% sequentially. The expected 20–25% net price improvement is also now effective, while management said the product has less than 2% addressable-market penetration.
- DF2 had been adopted by more than 150 of roughly 300 U.S. children’s hospitals, with high margins and no inventory requirement. The preview flagged specialty-bracing growth but did not anticipate this specific scale of hospital adoption or the stated economics.

### operating_profitability (449)
- B&G’s Q2 adjusted EBITDA was $60.4 million, above the preview’s modeled $56–58 million, and its 15.8% margin exceeded the estimated 14.3–14.7%. The result was aided by the higher-margin acquisitions and tariff refunds.
- Gross margin reached 44.1%, above the preview’s estimated 43.0–43.5% and its key 43.5%+ watch level. This was a stronger Q2 margin result than the preview’s base case of modest expansion.
- Q2 gross margin was 73%, below the preview’s roughly 76% estimate and below its 75% concern threshold. Management attributed the decline from Q1 to higher perpetual software licenses and expects a recovery next quarter, while retaining the 77% long-term target.

### revenue (605)
- Same-store revenue grew just 3%, a sharp deceleration from Q1’s 13.1% and below the preview’s watchpoint that low-single-digit growth would suggest Q1’s strength might have been a pull-forward. The call did not provide a same-store unit-growth rate.
- MEC reported Q2 sales of $163 million, above the preview’s $150.6 million consensus and the company’s $145–155 million guide. That is a clear upside surprise, though organic growth was 9.2% excluding AccuFab.
- Asia delivered unusually strong growth that the preview did not identify as an expected driver: organic sales rose 18% year over year and 20% sequentially, led by electronics, high-performance computing, and functional additives.

### strategy_corporate_events (122)
- The preview focused on whether the company would make cost and strategic changes, but did not anticipate a specific move away from broad direct-to-consumer TV advertising. ARS said it was shifting toward lower-cost, targeted provider-focused channels such as social media and search; the savings goal is positive, while the effectiveness of the new approach is not yet established.
- Five acquisitions had been completed year to date, representing about $165 million of annualized revenue—more than the preview’s expectation of four deals totaling about $150 million.
- The company disclosed a concrete pipeline of roughly $25 million in additional asset transactions, with possible closings by year-end. The preview anticipated continued asset sales but did not specify a comparable pending transaction pipeline.

### 4e. Stability

Propose a taxonomy from a different sample of events (`seed=1`), assign 1,000 items under it, and compare with your current version on those items. A low NMI means the dimensions depend on which events happened to be sampled; read the crosstab to see which ones disagree.

In [33]:
CURRENT = "v2"
ALT = "alt_seed1"

if grouping.taxonomy_path(ALT).exists():
    tax_alt = grouping.load_taxonomy(ALT)
else:
    tax_alt = grouping.propose_taxonomy(items_df, n_events=80, seed=1)
    grouping.save_taxonomy(tax_alt, ALT)

check_items = items_df.sample(1000, random_state=0)
grouping.assign_items(check_items, tax_alt, ALT)

nmi, table = grouping.agreement(grouping.load_assignments(CURRENT), grouping.load_assignments(ALT))
print(f"Agreement {CURRENT} vs {ALT}: NMI = {nmi:.3f}")
table

Assigning 1000 items in 25 batches (0 already done) with gpt-6-luna...
[1/25] 40/40 assigned
[2/25] 40/40 assigned
[3/25] 40/40 assigned
[4/25] 40/40 assigned
[5/25] 39/40 assigned
[6/25] 40/40 assigned
[7/25] 40/40 assigned
[8/25] 40/40 assigned
[9/25] 40/40 assigned
[10/25] 40/40 assigned
[11/25] 40/40 assigned
[12/25] 40/40 assigned
[13/25] 40/40 assigned
[14/25] 40/40 assigned
[15/25] 40/40 assigned
[16/25] 40/40 assigned
[17/25] 40/40 assigned
[18/25] 40/40 assigned
[19/25] 40/40 assigned
[20/25] 40/40 assigned
[21/25] 40/40 assigned
[22/25] 40/40 assigned
[23/25] 40/40 assigned
[24/25] 40/40 assigned
[25/25] 40/40 assigned
Done. 999 written, 1 missing, 0 batches failed; call again to retry.
Agreement v2 vs alt_seed1: NMI = 0.640

dimension_b,accounting_tax_special_items,balance_sheet_financing,capital_allocation,cash_flow,commercial_agreements_access,corporate_strategy_transactions,costs_efficiency,demand_customer_activity,disclosure_management_communication,earnings,operating_execution_capacity,operating_profitability,other,pricing_monetization_mix,product_development_regulation,revenue
dimension_a,,,,,,,,,,,,,,,,
accounting_tax_special_items,20,0,0,0,0,0,1,0,1,0,0,2,0,0,0,0
bottom_line_earnings,2,0,0,0,0,0,0,0,0,79,0,2,0,0,0,0
capital_allocation,1,1,30,0,0,0,0,0,0,0,0,0,0,0,0,0
cash_balance_sheet_liquidity,0,35,1,23,0,0,0,0,0,0,0,0,0,0,0,0
commercial_economics,0,0,1,0,24,0,0,2,0,0,0,0,0,16,1,0
costs_expenses,2,0,0,0,1,0,35,0,0,0,2,2,0,1,0,0
development_execution_regulatory,1,0,0,0,3,0,0,2,0,0,8,0,0,0,45,1
disclosure_delivery,0,0,0,0,0,0,0,1,2,0,0,0,0,0,0,0
external_environment,0,0,0,0,0,0,1,7,2,0,0,0,0,2,6,0
financing_capital_structure,0,11,2,0,1,0,0,0,0,0,0,0,0,0,3,0
forward_guidance,0,1,5,13,0,0,7,8,4,21,9,41,0,7,1,82
operating_kpis,0,3,1,1,3,0,1,94,0,0,24,5,1,2,1,11
operating_profitability,1,0,0,0,0,0,0,0,0,0,0,93,0,0,0,0
revenue,0,0,0,0,0,0,0,2,0,0,0,0,0,2,0,143
strategy_corporate_events,0,1,1,0,4,20,3,0,0,0,0,0,0,0,0,0

## 5. Extend to train_rest and test

Run the same two steps as discovery on the other events, with the taxonomy frozen at **v2**:

- **train_rest**: the 576 train events outside the discovery sample.
- **test**: the 289 test events. Extract and assign them now, but do not look at their returns until the model is fixed.

Each set gets its own files: `data/surprise/<set>_extractions.jsonl` and `data/surprise/taxonomy/assignments_v2_<set>.jsonl`. Both resume like before. Extraction uses `extraction.DEFAULT_MODEL` at `DEFAULT_EFFORT`, the same as discovery; assignment uses `grouping.ASSIGN_MODEL`.

Cost: about 865 extraction calls plus about 170 assignment batches.

In [34]:
from suprise_dim import dataset

FROZEN = "v2"
tax = grouping.load_taxonomy(FROZEN)
sets = dataset.event_sets(split, events_by_id)
print({name: len(evs) for name, evs in sets.items()})
print("discovery extraction model(s):", {r["model"] for r in extraction.load_extractions()}, "| now:", extraction.DEFAULT_MODEL, extraction.DEFAULT_EFFORT)

{'discovery': 500, 'train_rest': 576, 'test': 289}
discovery extraction model(s): {'gpt-6-luna'} | now: gpt-6-luna medium

### 5a. Extract surprises

Set `N` to a small number first as a smoke test, then `None`.

In [36]:
N = None  # None for every event in the set

for name in ("train_rest", "test"):
    evs = sets[name][:N] if N else sets[name]
    extraction.run_extraction(evs, out_path=data.extractions_path(name))

Extracting 566 events (10 already done) with gpt-6-luna...
[1/566] ea_HSIC_Q2_2026: 6 surprises
[2/566] ea_SHLS_Q2_2026: 8 surprises
[3/566] ea_FWRG_Q2_2026: 10 surprises
[4/566] ea_RYTM_Q2_2026: 10 surprises
[5/566] ea_LDOS_Q2_2026: 9 surprises
[6/566] ea_TREX_Q2_2026: 8 surprises
[7/566] ea_WAT_Q2_2026: 10 surprises
[8/566] ea_DOCN_Q2_2026: 8 surprises
[9/566] ea_ANDE_Q2_2026: 3 surprises
[10/566] ea_WHR_Q2_2026: 7 surprises
[11/566] ea_AHCO_Q2_2026: 10 surprises
[12/566] ea_APO_Q2_2026: 10 surprises
[13/566] ea_W_Q2_2026: 12 surprises
[14/566] ea_BALL_Q2_2026: 12 surprises
[15/566] ea_BR_Q4_2026: 8 surprises
[16/566] ea_BRBR_Q3_2026: 10 surprises
[17/566] ea_CAT_Q2_2026: 11 surprises
[18/566] ea_CERT_Q2_2026: 7 surprises
[19/566] ea_PVLA_Q2_2026: 7 surprises
[20/566] ea_NPO_Q2_2026: 8 surprises
[21/566] ea_SEAT_Q2_2026: 6 surprises
[22/566] ea_IDXX_Q2_2026: 7 surprises
[23/566] ea_XMTR_Q2_2026: 6 surprises
[24/566] ea_AIN_Q2_2026: 8 surprises
[25/566] ea_ZBRA_Q2_2026: 8 surprises
[26/566] ea_BRKR_Q2_2026: 12 surprises
[27/566] ea_ENTG_Q2_2026: 13 surprises
[28/566] ea_INGR_Q2_2026: 10 surprises
[29/566] ea_INFU_Q2_2026: 6 surprises
[30/566] ea_NRG_Q2_2026: 8 surprises
[31/566] ea_MD_Q2_2026: 8 surprises
[32/566] ea_PRKS_Q2_2026: 9 surprises
[33/566] ea_STRL_Q2_2026: 10 surprises
[34/566] ea_GPK_Q2_2026: 9 surprises
[35/566] ea_TPB_Q2_2026: 8 surprises
[36/566] ea_CTRI_Q2_2026: 8 surprises
[37/566] ea_HVT_Q2_2026: 6 surprises
[38/566] ea_RSVR_Q1_2027: 6 surprises
[39/566] ea_PFE_Q2_2026: 10 surprises
[40/566] ea_IPGP_Q2_2026: 7 surprises
[41/566] ea_JBTM_Q2_2026: 8 surprises
[42/566] ea_GWW_Q2_2026: 11 surprises
[43/566] ea_UONEK_Q2_2026: 9 surprises
[44/566] ea_RAIL_Q2_2026: 9 surprises
[45/566] ea_POWL_Q3_2026: 8 surprises
[46/566] ea_TDG_Q3_2026: 6 surprises
[47/566] ea_PNW_Q2_2026: 8 surprises
[48/566] ea_TKR_Q2_2026: 12 surprises
[49/566] ea_WLK_Q2_2026: 6 surprises
[50/566] ea_ACEL_Q2_2026: 9 surprises
[51/566] ea_ACAD_Q2_2026: 10 surprises
[52/566] ea_ARWR_Q3_2026: 7 surprises
[53/566] ea_ALIT_Q2_2026: 11 surprises
[54/566] ea_EVTC_Q2_2026: 12 surprises
[55/566] ea_CXDO_Q2_2026: 10 surprises
[56/566] ea_MQ_Q2_2026: 10 surprises
[57/566] ea_J_Q3_2026: 6 surprises
[58/566] ea_GILD_Q2_2026: 8 surprises
[59/566] ea_BKNG_Q2_2026: 13 surprises
[60/566] ea_PCRX_Q2_2026: 8 surprises
[61/566] ea_PRCT_Q2_2026: 7 surprises
[62/566] ea_TRNS_Q1_2027: 4 surprises
[63/566] ea_RRR_Q2_2026: 8 surprises
[64/566] ea_SWIM_Q2_2026: 8 surprises
[65/566] ea_TYGO_Q2_2026: 10 surprises
[66/566] ea_TVTX_Q2_2026: 5 surprises
[67/566] ea_WYNN_Q2_2026: 8 surprises
[68/566] ea_ACNT_Q2_2026: 9 surprises
[69/566] ea_ZETA_Q2_2026: 12 surprises
[70/566] ea_AMWL_Q2_2026: 9 surprises
[71/566] ea_ATOM_Q2_2026: 10 surprises
[72/566] ea_AMD_Q2_2026: 8 surprises
[73/566] ea_BIO_Q2_2026: 8 surprises
[74/566] ea_CRCT_Q2_2026: 7 surprises
[75/566] ea_CACC_Q2_2026: 4 surprises
[76/566] ea_COMP_Q2_2026: 9 surprises
[77/566] ea_FOA_Q2_2026: 7 surprises
[78/566] ea_DVA_Q2_2026: 9 surprises
[79/566] ea_GIC_Q2_2026: 10 surprises
[80/566] ea_EGHT_Q1_2027: 9 surprises
[81/566] ea_FRSH_Q2_2026: 6 surprises
[82/566] ea_HCKT_Q2_2026: 12 surprises
[83/566] ea_KODK_Q2_2026: 7 surprises
[84/566] ea_KTOS_Q2_2026: 9 surprises
[85/566] ea_LDI_Q2_2026: 9 surprises
[86/566] ea_RARE_Q2_2026: 8 surprises
[87/566] ea_MTCH_Q2_2026: 8 surprises
[88/566] ea_LUMN_Q2_2026: 12 surprises
[89/566] ea_LCID_Q2_2026: 7 surprises
[90/566] ea_WK_Q2_2026: 4 surprises
[91/566] ea_PCTY_Q4_2026: 6 surprises
[92/566] ea_ACTG_Q2_2026: 9 surprises
[93/566] ea_EPC_Q3_2026: 7 surprises
[94/566] ea_DT_Q1_2027: 8 surprises
[95/566] ea_DIBS_Q2_2026: 7 surprises
[96/566] ea_CVS_Q2_2026: 11 surprises
[97/566] ea_EVGO_Q2_2026: 7 surprises
[98/566] ea_EQH_Q2_2026: 8 surprises
[99/566] ea_EXTR_Q4_2026: 8 surprises
[100/566] ea_GERN_Q2_2026: 6 surprises
[101/566] ea_GPN_Q2_2026: 6 surprises
[102/566] ea_FRPT_Q2_2026: 11 surprises
[103/566] ea_NYT_Q2_2026: 6 surprises
[104/566] ea_KLTR_Q2_2026: 7 surprises
[105/566] ea_LINE_Q2_2026: 9 surprises
[106/566] ea_PRMB_Q2_2026: 5 surprises
[107/566] ea_PODD_Q2_2026: 9 surprises
[108/566] ea_RXRX_Q2_2026: 6 surprises
[109/566] ea_SHAK_Q2_2026: 10 surprises
[110/566] ea_UBER_Q2_2026: 10 surprises
[111/566] ea_VYX_Q2_2026: 8 surprises
[112/566] ea_YOU_Q2_2026: 10 surprises
[113/566] ea_ANGI_Q2_2026: 12 surprises
[114/566] ea_ADV_Q2_2026: 7 surprises
[115/566] ea_AMPX_Q2_2026: 12 surprises
[116/566] ea_COR_Q3_2026: 9 surprises
[117/566] ea_CDW_Q2_2026: 10 surprises
[118/566] ea_BCRX_Q2_2026: 7 surprises
[119/566] ea_EOSE_Q2_2026: 5 surprises
[120/566] ea_GFF_Q3_2026: 6 surprises
[121/566] ea_LAW_Q2_2026: 10 surprises
[122/566] ea_HLLY_Q2_2026: 8 surprises
[123/566] ea_LCII_Q2_2026: 9 surprises
[124/566] ea_NXDR_Q2_2026: 4 surprises
[125/566] ea_ZBH_Q2_2026: 8 surprises
[126/566] ea_OFIX_Q2_2026: 8 surprises
[127/566] ea_CPSH_Q2_2026: 9 surprises
[128/566] ea_CRBG_Q2_2026: 7 surprises
[129/566] ea_FRPH_Q2_2026: 6 surprises
[130/566] ea_BCO_Q2_2026: 10 surprises
[131/566] ea_LMB_Q2_2026: 6 surprises
[132/566] ea_MTRN_Q2_2026: 12 surprises
[133/566] ea_KHC_Q2_2026: 8 surprises
[134/566] ea_IFF_Q2_2026: 11 surprises
[135/566] ea_OC_Q2_2026: 6 surprises
[136/566] ea_FUBO_Q3_2026: 6 surprises
[137/566] ea_VPG_Q2_2026: 8 surprises
[138/566] ea_VSH_Q2_2026: 10 surprises
[139/566] ea_BATRK_Q2_2026: 8 surprises
[140/566] ea_ARDT_Q2_2026: 9 surprises
[141/566] ea_CHH_Q2_2026: 10 surprises
[142/566] ea_FTEK_Q2_2026: 9 surprises
[143/566] ea_HL_Q2_2026: 9 surprises
[144/566] ea_OESX_Q1_2027: 11 surprises
[145/566] ea_OSS_Q2_2026: 7 surprises
[146/566] ea_HGTY_Q2_2026: 9 surprises
[147/566] ea_TALO_Q2_2026: 10 surprises
[148/566] ea_VOYA_Q2_2026: 7 surprises
[149/566] ea_VTOL_Q2_2026: 5 surprises
[150/566] ea_GBLI_Q2_2026: 7 surprises
[151/566] ea_ECVT_Q2_2026: 7 surprises
[152/566] ea_HY_Q2_2026: 7 surprises
[153/566] ea_DK_Q2_2026: 8 surprises
[154/566] ea_KAI_Q2_2026: 10 surprises
[155/566] ea_IPAR_Q2_2026: 7 surprises
[156/566] ea_OGS_Q2_2026: 6 surprises
[157/566] ea_SWX_Q2_2026: 5 surprises
[158/566] ea_NWN_Q2_2026: 9 surprises
[159/566] ea_MOS_Q2_2026: 10 surprises
[160/566] ea_PRU_Q2_2026: 8 surprises
[161/566] ea_USNA_Q2_2026: 8 surprises
[162/566] ea_WTRG_Q2_2026: 4 surprises
[163/566] ea_WEYS_Q2_2026: 6 surprises
[164/566] ea_WTTR_Q2_2026: 8 surprises
[165/566] ea_PACS_Q2_2026: 6 surprises
[166/566] ea_CRVL_Q1_2027: 4 surprises
[167/566] ea_AGL_Q2_2026: 7 surprises
[168/566] ea_SMRT_Q2_2026: 7 surprises
[169/566] ea_ATEN_Q2_2026: 7 surprises
[170/566] ea_AVT_Q4_2026: 7 surprises
[171/566] ea_BLBD_Q3_2026: 8 surprises
[172/566] ea_VIR_Q2_2026: 6 surprises
[173/566] ea_MCK_Q1_2027: 10 surprises
[174/566] ea_WMG_Q3_2026: 4 surprises
[175/566] ea_ZVIA_Q2_2026: 7 surprises
[176/566] ea_ALTO_Q2_2026: 8 surprises
[177/566] ea_BBSI_Q2_2026: 6 surprises
[178/566] ea_HNST_Q2_2026: 9 surprises
[179/566] ea_DHX_Q2_2026: 9 surprises
[180/566] ea_MELI_Q2_2026: 9 surprises
[181/566] ea_OSUR_Q2_2026: 9 surprises
[182/566] ea_MSI_Q2_2026: 8 surprises
[183/566] ea_NVST_Q2_2026: 11 surprises
[184/566] ea_SITM_Q2_2026: 9 surprises
[185/566] ea_SMR_Q2_2026: 8 surprises
[186/566] ea_ACT_Q2_2026: 5 surprises
[187/566] ea_SOUN_Q2_2026: 12 surprises
[188/566] ea_VEL_Q2_2026: 5 surprises
[189/566] ea_CMRC_Q2_2026: 6 surprises
[190/566] ea_ALB_Q2_2026: 8 surprises
[191/566] ea_COLL_Q2_2026: 9 surprises
[192/566] ea_BDX_Q3_2026: 6 surprises
[193/566] ea_DNUT_Q2_2026: 6 surprises
[194/566] ea_EPAM_Q2_2026: 11 surprises
[195/566] ea_HAE_Q1_2027: 9 surprises
[196/566] ea_IMVT_Q1_2027: 6 surprises
[197/566] ea_EVH_Q2_2026: 11 surprises
[198/566] ea_KLIC_Q3_2026: 11 surprises
[199/566] ea_KDP_Q2_2026: 10 surprises
[200/566] ea_KMPR_Q2_2026: 8 surprises
[201/566] ea_NTLA_Q2_2026: 5 surprises
[202/566] ea_PLNT_Q2_2026: 6 surprises
[203/566] ea_NUVB_Q2_2026: 10 surprises
[204/566] ea_QBTS_Q2_2026: 5 surprises
[205/566] ea_OSCR_Q2_2026: 8 surprises
[206/566] ea_PZZA_Q2_2026: 10 surprises
[207/566] ea_SRRK_Q2_2026: 4 surprises
[208/566] ea_SGI_Q2_2026: 9 surprises
[209/566] ea_TFX_Q2_2026: 8 surprises
[210/566] ea_UMAC_Q2_2026: 8 surprises
[211/566] ea_VCTR_Q2_2026: 9 surprises
[212/566] ea_WBD_Q2_2026: 7 surprises
[213/566] ea_TSQ_Q2_2026: 10 surprises
[214/566] ea_WRBY_Q2_2026: 6 surprises
[215/566] ea_ACLS_Q2_2026: 7 surprises
[216/566] ea_BKSY_Q2_2026: 9 surprises
[217/566] ea_ARHS_Q2_2026: 10 surprises
[218/566] ea_BRLT_Q2_2026: 10 surprises
[219/566] ea_DCTH_Q2_2026: 7 surprises
[220/566] ea_EE_Q2_2026: 6 surprises
[221/566] ea_CCOI_Q2_2026: 10 surprises
[222/566] ea_DRVN_Q2_2026: 7 surprises
[223/566] ea_CGNX_Q2_2026: 8 surprises
[224/566] ea_FA_Q2_2026: 9 surprises
[225/566] ea_FLNC_Q3_2026: 13 surprises
[226/566] ea_FOUR_Q2_2026: 8 surprises
[227/566] ea_FTDR_Q2_2026: 7 surprises
[228/566] ea_GNE_Q2_2026: 6 surprises
[229/566] ea_GOGO_Q2_2026: 9 surprises
[230/566] ea_IOVA_Q2_2026: 10 surprises
[231/566] ea_FOXA_Q4_2026: 10 surprises
[232/566] ea_LFST_Q2_2026: 8 surprises
[233/566] ea_LXRX_Q2_2026: 7 surprises
[234/566] ea_NC_Q2_2026: 9 surprises
[235/566] ea_MNTK_Q2_2026: 8 surprises
[236/566] ea_NVAX_Q2_2026: 5 surprises
[237/566] ea_OCGN_Q2_2026: 8 surprises
[238/566] ea_PLTK_Q2_2026: 10 surprises
[239/566] ea_PBH_Q1_2027: 7 surprises
[240/566] ea_TRIP_Q2_2026: 7 surprises
[241/566] ea_VAC_Q2_2026: 10 surprises
[242/566] ea_WD_Q2_2026: 6 surprises
[243/566] ea_VTRS_Q2_2026: 10 surprises
[244/566] ea_CARS_Q2_2026: 8 surprises
[245/566] ea_ALL_Q2_2026: 7 surprises
[246/566] ea_BGSF_Q2_2026: 7 surprises
[247/566] ea_EZPW_Q3_2026: 6 surprises
[248/566] ea_FG_Q2_2026: 8 surprises
[249/566] ea_CSV_Q2_2026: 7 surprises
[250/566] ea_KNTK_Q2_2026: 8 surprises
[251/566] ea_KELYA_Q2_2026: 9 surprises
[252/566] ea_III_Q2_2026: 10 surprises
[253/566] ea_MUR_Q2_2026: 7 surprises
[254/566] ea_NSIT_Q2_2026: 9 surprises
[255/566] ea_NNBR_Q2_2026: 9 surprises
[256/566] ea_SNEX_Q3_2026: 6 surprises
[257/566] ea_RL_Q1_2027: 8 surprises
[258/566] ea_ALNT_Q2_2026: 8 surprises
[259/566] ea_BKV_Q2_2026: 6 surprises
[260/566] ea_UGI_Q3_2026: 7 surprises
[261/566] ea_ATO_Q3_2026: 7 surprises
[262/566] ea_CW_Q2_2026: 8 surprises
[263/566] ea_LEE_Q3_2026: 6 surprises
[264/566] ea_IBP_Q2_2026: 7 surprises
[265/566] ea_HWM_Q2_2026: 4 surprises
[266/566] ea_MAGN_Q3_2026: 8 surprises
[267/566] ea_PRI_Q2_2026: 6 surprises
[268/566] ea_MLR_Q2_2026: 8 surprises
[269/566] ea_NINE_Q2_2026: 9 surprises
[270/566] ea_PRTH_Q2_2026: 10 surprises
[271/566] ea_REPX_Q2_2026: 8 surprises
[272/566] ea_TNC_Q2_2026: 9 surprises
[273/566] ea_UVV_Q1_2027: 5 surprises
[274/566] ea_APA_Q2_2026: 6 surprises
[275/566] ea_MMI_Q2_2026: 9 surprises
[276/566] ea_WTI_Q2_2026: 11 surprises
[277/566] ea_ATNI_Q2_2026: 6 surprises
[278/566] ea_BKH_Q2_2026: 6 surprises
[279/566] ea_USPH_Q2_2026: 9 surprises
[280/566] ea_LQDT_Q3_2026: 10 surprises
[281/566] ea_CF_Q2_2026: 8 surprises
[282/566] ea_LB_Q2_2026: 7 surprises
[283/566] ea_GHM_Q1_2027: 6 surprises
[284/566] ea_FNF_Q2_2026: 7 surprises
[285/566] ea_MTDR_Q2_2026: 9 surprises
[286/566] ea_LOAR_Q2_2026: 6 surprises
[287/566] ea_LNG_Q2_2026: 6 surprises
[288/566] ea_CHRD_Q2_2026: 7 surprises
[289/566] ea_MUSA_Q2_2026: 6 surprises
[290/566] ea_SD_Q2_2026: 9 surprises
[291/566] ea_DXPE_Q2_2026: 9 surprises
[292/566] ea_AIP_Q2_2026: 6 surprises
[293/566] ea_AORT_Q2_2026: 9 surprises
[294/566] ea_BARK_Q1_2027: 6 surprises
[295/566] ea_ASLE_Q2_2026: 9 surprises
[296/566] ea_ARCT_Q2_2026: 9 surprises
[297/566] ea_BETR_Q2_2026: 6 surprises
[298/566] ea_CLNE_Q2_2026: 7 surprises
[299/566] ea_BLNK_Q2_2026: 10 surprises
[300/566] ea_DFLI_Q2_2026: 6 surprises
[301/566] ea_BMRN_Q2_2026: 11 surprises
[302/566] ea_DNLI_Q2_2026: 7 surprises
[303/566] ea_CYTK_Q2_2026: 9 surprises
[304/566] ea_CTSO_Q2_2026: 10 surprises
[305/566] ea_FLL_Q2_2026: 6 surprises
[306/566] ea_ECOR_Q2_2026: 9 surprises
[307/566] ea_FNKO_Q2_2026: 9 surprises
[308/566] ea_HYPR_Q2_2026: 5 surprises
[309/566] ea_GRDN_Q2_2026: 6 surprises
[310/566] ea_GEVO_Q2_2026: 2 surprises
[311/566] ea_ICFI_Q2_2026: 6 surprises
[312/566] ea_LCTX_Q2_2026: 8 surprises
[313/566] ea_NEPH_Q2_2026: 7 surprises
[314/566] ea_FOXF_Q2_2026: 12 surprises
[315/566] ea_NEWT_Q2_2026: 4 surprises
[316/566] ea_LOCO_Q2_2026: 7 surprises
[317/566] ea_NRDS_Q2_2026: 7 surprises
[318/566] ea_NTRA_Q2_2026: 10 surprises
[319/566] ea_PBYI_Q2_2026: 8 surprises
[320/566] ea_PLSE_Q2_2026: 8 surprises
[321/566] ea_REFR_Q2_2026: 7 surprises
[322/566] ea_PRDO_Q2_2026: 8 surprises
[323/566] ea_RILY_Q2_2026: 7 surprises
[324/566] ea_RMD_Q4_2026: 8 surprises
[325/566] ea_SIGA_Q2_2026: 4 surprises
[326/566] ea_SKIN_Q2_2026: 9 surprises
[327/566] ea_SPT_Q2_2026: 10 surprises
[328/566] ea_TLSI_Q2_2026: 6 surprises
[329/566] ea_TBCH_Q2_2026: 7 surprises
[330/566] ea_UEIC_Q2_2026: 9 surprises
[331/566] ea_VRCA_Q2_2026: 6 surprises
[332/566] ea_WEAV_Q2_2026: 6 surprises
[333/566] ea_TXG_Q2_2026: 11 surprises
[334/566] ea_HCI_Q2_2026: 8 surprises
[335/566] ea_XPOF_Q2_2026: 6 surprises
[336/566] ea_ALTG_Q2_2026: 7 surprises
[337/566] ea_PGNY_Q2_2026: 8 surprises
[338/566] ea_ABNB_Q2_2026: 13 surprises
[339/566] ea_AMPH_Q2_2026: 7 surprises
[340/566] ea_AMN_Q2_2026: 12 surprises
[341/566] ea_CARG_Q2_2026: 7 surprises
[342/566] ea_ATLC_Q2_2026: 9 surprises
[343/566] ea_CENX_Q2_2026: 10 surprises
[344/566] ea_CTMX_Q2_2026: 3 surprises
[345/566] ea_CYRX_Q2_2026: 8 surprises
[346/566] ea_CART_Q2_2026: 9 surprises
[347/566] ea_DOCS_Q1_2027: 10 surprises
[348/566] ea_GRND_Q2_2026: 7 surprises
[349/566] ea_ESE_Q3_2026: 11 surprises
[350/566] ea_EXFY_Q2_2026: 5 surprises
[351/566] ea_HCAT_Q2_2026: 8 surprises
[352/566] ea_GTIM_Q3_2026: 9 surprises
[353/566] ea_INDI_Q2_2026: 12 surprises
[354/566] ea_INGN_Q2_2026: 7 surprises
[355/566] ea_LYFT_Q2_2026: 7 surprises
[356/566] ea_LIDR_Q2_2026: 8 surprises
[357/566] ea_INOD_Q2_2026: 7 surprises
[358/566] ea_NATR_Q2_2026: 10 surprises
[359/566] ea_NAVI_Q2_2026: 6 surprises
[360/566] ea_MRVI_Q2_2026: 11 surprises
[361/566] ea_NET_Q2_2026: 12 surprises
[362/566] ea_NRDY_Q2_2026: 6 surprises
[363/566] ea_REAL_Q2_2026: 7 surprises
[364/566] ea_ORGO_Q2_2026: 7 surprises
[365/566] ea_QDEL_Q2_2026: 8 surprises
[366/566] ea_NTGR_Q2_2026: 9 surprises
[367/566] ea_SG_Q2_2026: 9 surprises
[368/566] ea_SERV_Q2_2026: 10 surprises
[369/566] ea_WSC_Q2_2026: 6 surprises
[370/566] ea_ACMR_Q2_2026: 7 surprises
[371/566] ea_TTD_Q2_2026: 7 surprises
[372/566] ea_SUIG_Q2_2026: 7 surprises
[373/566] ea_ASTH_Q2_2026: 9 surprises
[374/566] ea_SVCO_Q2_2026: 8 surprises
[375/566] ea_AFL_Q2_2026: 7 surprises
[376/566] ea_ATKR_Q3_2026: 4 surprises
[377/566] ea_TMCI_Q2_2026: 8 surprises
[378/566] ea_EMBC_Q3_2026: 9 surprises
[379/566] ea_DOUG_Q2_2026: 6 surprises
[380/566] ea_GRPN_Q2_2026: 7 surprises
[381/566] ea_CPK_Q2_2026: 7 surprises
[382/566] ea_TILE_Q2_2026: 9 surprises
[383/566] ea_OKLO_Q2_2026: 8 surprises
[384/566] ea_MBI_Q2_2026: 6 surprises
[385/566] ea_ARKO_Q2_2026: 6 surprises
[386/566] ea_WEN_Q2_2026: 6 surprises
[387/566] ea_POST_Q3_2026: 8 surprises
[388/566] ea_RGCO_Q3_2026: 5 surprises
[389/566] ea_CON_Q2_2026: 11 surprises
[390/566] ea_SPB_Q3_2026: 11 surprises
[391/566] ea_ASIX_Q2_2026: 9 surprises
[392/566] ea_SSP_Q2_2026: 9 surprises
[393/566] ea_DTI_Q2_2026: 7 surprises
[394/566] ea_GEOS_Q3_2026: 6 surprises
[395/566] ea_MERC_Q2_2026: 8 surprises
[396/566] ea_MTW_Q2_2026: 10 surprises
[397/566] ea_ROAD_Q3_2026: 11 surprises
[398/566] ea_VST_Q2_2026: 7 surprises
[399/566] ea_GTN_Q2_2026: 10 surprises
[400/566] ea_TDS_Q2_2026: 9 surprises
[401/566] ea_ATMU_Q2_2026: 9 surprises
[402/566] ea_PPL_Q2_2026: 7 surprises
[403/566] ea_SBET_Q2_2026: 2 surprises
[404/566] ea_TUSK_Q2_2026: 10 surprises
[405/566] ea_AIRS_Q2_2026: 8 surprises
[406/566] ea_NABL_Q2_2026: 8 surprises
[407/566] ea_TH_Q2_2026: 9 surprises
[408/566] ea_JRSH_Q1_2027: 7 surprises
[409/566] ea_TLS_Q2_2026: 6 surprises
[410/566] ea_CNDT_Q2_2026: 10 surprises
[411/566] ea_GCMG_Q2_2026: 5 surprises
[412/566] ea_RDNT_Q2_2026: 6 surprises
[413/566] ea_AVD_Q2_2026: 5 surprises
[414/566] ea_SNDA_Q2_2026: 8 surprises
[415/566] ea_BNGO_Q2_2026: 7 surprises
[416/566] ea_CRC_Q2_2026: 11 surprises
[417/566] ea_CBLL_Q2_2026: 8 surprises
[418/566] ea_BBIO_Q2_2026: 9 surprises
[419/566] ea_FLNT_Q2_2026: 8 surprises
[420/566] ea_GUTS_Q2_2026: 7 surprises
[421/566] ea_GCTS_Q2_2026: 7 surprises
[422/566] ea_HFFG_Q2_2026: 8 surprises
[423/566] ea_HQI_Q2_2026: 5 surprises
[424/566] ea_PLUG_Q2_2026: 12 surprises
[425/566] ea_RIOT_Q2_2026: 12 surprises
[426/566] ea_MLAB_Q1_2027: 9 surprises
[427/566] ea_ALTI_Q2_2026: 6 surprises
[428/566] ea_AAON_Q2_2026: 6 surprises
[429/566] ea_TELA_Q2_2026: 6 surprises
[430/566] ea_ACHR_Q2_2026: 7 surprises
[431/566] ea_APEI_Q2_2026: 7 surprises
[432/566] ea_BW_Q2_2026: 4 surprises
[433/566] ea_CNNE_Q2_2026: 7 surprises
[434/566] ea_BODI_Q2_2026: 5 surprises
[435/566] ea_GPRO_Q2_2026: 7 surprises
[436/566] ea_DH_Q2_2026: 8 surprises
[437/566] ea_EXOD_Q2_2026: 7 surprises
[438/566] ea_DJT_Q2_2026: 5 surprises
[439/566] ea_HIMS_Q2_2026: 12 surprises
[440/566] ea_HNRG_Q2_2026: 5 surprises
[441/566] ea_KOPN_Q2_2026: 8 surprises
[442/566] ea_MVST_Q2_2026: 6 surprises
[443/566] ea_OPFI_Q2_2026: 6 surprises
[444/566] ea_NUS_Q2_2026: 7 surprises
[445/566] ea_RUM_Q2_2026: 4 surprises
[446/566] ea_PAL_Q2_2026: 8 surprises
[447/566] ea_TCMD_Q2_2026: 8 surprises
[448/566] ea_WBTN_Q2_2026: 9 surprises
[449/566] ea_SRFM_Q2_2026: 5 surprises
[450/566] ea_ALCO_Q3_2026: 9 surprises
[451/566] ea_HBIO_Q2_2026: 7 surprises
[452/566] ea_BCAX_Q2_2026: 4 surprises
[453/566] ea_LWLG_Q2_2026: 4 surprises
[454/566] ea_INTS_Q2_2026: 3 surprises
[455/566] ea_AP_Q2_2026: 8 surprises
[456/566] ea_NGS_Q2_2026: 4 surprises
[457/566] ea_MASS_Q2_2026: 5 surprises
[458/566] ea_STIM_Q2_2026: 11 surprises
[459/566] ea_VSTS_Q3_2026: 10 surprises
[460/566] ea_BKD_Q2_2026: 4 surprises
[461/566] ea_XTNT_Q2_2026: 6 surprises
[462/566] ea_TISI_Q2_2026: 9 surprises
[463/566] ea_JBI_Q2_2026: 8 surprises
[464/566] ea_HLIO_Q2_2026: 8 surprises
[465/566] ea_TONX_Q2_2026: 4 surprises
[466/566] ea_SMC_Q2_2026: 7 surprises
[467/566] ea_KLXE_Q2_2026: 8 surprises
[468/566] ea_HPK_Q2_2026: 6 surprises
[469/566] ea_IMNN_Q2_2026: 5 surprises
[470/566] ea_ABSI_Q2_2026: 5 surprises
[471/566] ea_UAMY_Q2_2026: 8 surprises
[472/566] ea_CDXS_Q2_2026: 9 surprises
[473/566] ea_GRWG_Q2_2026: 9 surprises
[474/566] ea_FF_Q2_2026: 9 surprises
[475/566] ea_EVLV_Q2_2026: 9 surprises
[476/566] ea_HRB_Q4_2026: 9 surprises
[477/566] ea_PRSO_Q2_2026: 5 surprises
[478/566] ea_LENZ_Q2_2026: 9 surprises
[479/566] ea_NRGV_Q2_2026: 8 surprises
[480/566] ea_SNAL_Q2_2026: 7 surprises
[481/566] ea_STXS_Q2_2026: 7 surprises
[482/566] ea_SEER_Q2_2026: 9 surprises
[483/566] ea_NN_Q2_2026: 5 surprises
[484/566] ea_ATRO_Q2_2026: 11 surprises
[485/566] ea_INTZ_Q2_2026: 3 surprises
[486/566] ea_GWH_Q2_2026: 6 surprises
[487/566] ea_PXLW_Q2_2026: 8 surprises
[488/566] ea_SES_Q2_2026: 6 surprises
[489/566] ea_LQDA_Q2_2026: 3 surprises
[490/566] ea_HUMA_Q2_2026: 8 surprises
[491/566] ea_ALT_Q2_2026: 4 surprises
[492/566] ea_PLX_Q2_2026: 7 surprises
[493/566] ea_KTB_Q2_2026: 7 surprises
[494/566] ea_ATEX_Q1_2027: 6 surprises
[495/566] ea_SWAG_Q2_2026: 5 surprises
[496/566] ea_PODC_Q1_2027: 3 surprises
[497/566] ea_SLNG_Q2_2026: 7 surprises
[498/566] ea_PFGC_Q4_2026: 3 surprises
[499/566] ea_LVO_Q1_2027: 9 surprises
[500/566] ea_AVIR_Q2_2026: 4 surprises
[501/566] ea_BCDA_Q2_2026: 10 surprises
[502/566] ea_DERM_Q2_2026: 6 surprises
[503/566] ea_ICU_Q2_2026: 4 surprises
[504/566] ea_COHR_Q4_2026: 9 surprises
[505/566] ea_DLPN_Q2_2026: 8 surprises
[506/566] ea_GO_Q2_2026: 8 surprises
[507/566] ea_OMER_Q2_2026: 7 surprises
[508/566] ea_SPRU_Q2_2026: 5 surprises
[509/566] ea_SKYX_Q2_2026: 4 surprises
[510/566] ea_KURA_Q2_2026: 9 surprises
[511/566] ea_RRGB_Q2_2026: 8 surprises
[512/566] ea_CVV_Q2_2026: 7 surprises
[513/566] ea_CRWS_Q1_2027: 7 surprises
[514/566] ea_ALLO_Q2_2026: 7 surprises
[515/566] ea_USIO_Q2_2026: 9 surprises
[516/566] ea_FOSL_Q2_2026: 8 surprises

### 5b. Assign every surprise to a v2 dimension

In [37]:
for name in ("train_rest", "test"):
    ids = {e["event_id"] for e in sets[name]}
    recs = [r for r in extraction.load_extractions(data.extractions_path(name)) if r["event_id"] in ids]
    grouping.assign_items(grouping.surprise_items(recs), tax, dataset.assignment_version(FROZEN, name))

Assigning 4448 items in 112 batches (0 already done) with gpt-6-luna...
[1/112] 40/40 assigned
[2/112] 40/40 assigned
[3/112] 40/40 assigned
[4/112] 40/40 assigned
[5/112] 40/40 assigned
[6/112] 40/40 assigned
[7/112] 40/40 assigned
[8/112] 40/40 assigned
[9/112] 40/40 assigned
[10/112] 40/40 assigned
[11/112] 40/40 assigned
[12/112] 40/40 assigned
[13/112] 40/40 assigned
[14/112] 40/40 assigned
[15/112] 40/40 assigned
[16/112] 40/40 assigned
[17/112] 40/40 assigned
[18/112] 40/40 assigned
[19/112] 40/40 assigned
[20/112] 40/40 assigned
[21/112] 40/40 assigned
[22/112] 40/40 assigned
[23/112] 40/40 assigned
[24/112] 40/40 assigned
[25/112] 40/40 assigned
[26/112] 40/40 assigned
[27/112] 40/40 assigned
[28/112] 40/40 assigned
[29/112] 40/40 assigned
[30/112] 40/40 assigned
[31/112] 40/40 assigned
[32/112] 40/40 assigned
[33/112] 40/40 assigned
[34/112] 40/40 assigned
[35/112] 40/40 assigned
[36/112] 40/40 assigned
[37/112] 40/40 assigned
[38/112] 40/40 assigned
[39/112] 40/40 assigned
[40/112] 40/40 assigned
[41/112] 40/40 assigned
[42/112] 40/40 assigned
[43/112] 40/40 assigned
[44/112] 40/40 assigned
[45/112] 40/40 assigned
[46/112] 40/40 assigned
[47/112] 40/40 assigned
[48/112] 40/40 assigned
[49/112] 40/40 assigned
[50/112] 40/40 assigned
[51/112] 40/40 assigned
[52/112] 40/40 assigned
[53/112] 40/40 assigned
[54/112] 40/40 assigned
[55/112] 40/40 assigned
[56/112] 40/40 assigned
[57/112] 40/40 assigned
[58/112] 40/40 assigned
[59/112] 40/40 assigned
[60/112] 40/40 assigned
[61/112] 40/40 assigned
[62/112] 40/40 assigned
[63/112] 40/40 assigned
[64/112] 40/40 assigned
[65/112] 40/40 assigned
[66/112] 40/40 assigned
[67/112] 40/40 assigned
[68/112] 40/40 assigned
[69/112] 40/40 assigned
[70/112] 40/40 assigned
[71/112] 40/40 assigned
[72/112] 40/40 assigned
[73/112] 40/40 assigned
[74/112] 40/40 assigned
[75/112] 40/40 assigned
[76/112] 40/40 assigned
[77/112] 40/40 assigned
[78/112] 40/40 assigned
[79/112] 40/40 assigned
[80/112] 40/40 assigned
[81/112] 40/40 assigned
[82/112] 40/40 assigned
[83/112] 40/40 assigned
[84/112] 40/40 assigned
[85/112] 40/40 assigned
[86/112] 40/40 assigned
[87/112] 40/40 assigned
[88/112] 40/40 assigned
[89/112] 40/40 assigned
[90/112] 40/40 assigned
[91/112] 40/40 assigned
[92/112] 40/40 assigned
[93/112] 40/40 assigned
[94/112] 40/40 assigned
[95/112] 40/40 assigned
[96/112] 40/40 assigned
[97/112] 40/40 assigned
[98/112] 40/40 assigned
[99/112] 40/40 assigned
[100/112] 40/40 assigned
[101/112] 40/40 assigned
[102/112] 40/40 assigned
[103/112] 40/40 assigned
[104/112] 40/40 assigned
[105/112] 40/40 assigned
[106/112] 40/40 assigned
[107/112] 40/40 assigned
[108/112] 40/40 assigned
[109/112] 8/8 assigned
[110/112] 40/40 assigned
[111/112] 40/40 assigned
[112/112] 40/40 assigned
Done. 4448 written, 0 missing, 0 batches failed; call again to retry.
Assigning 2188 items in 55 batches (0 already done) with gpt-6-luna...
[1/55] 40/40 assigned
[2/55] 40/40 assigned
[3/55] 40/40 assigned
[4/55] 40/40 assigned
[5/55] 40/40 assigned
[6/55] 40/40 assigned
[7/55] 40/40 assigned
[8/55] 40/40 assigned
[9/55] 40/40 assigned
[10/55] 40/40 assigned
[11/55] 40/40 assigned
[12/55] 40/40 assigned
[13/55] 40/40 assigned
[14/55] 40/40 assigned
[15/55] 40/40 assigned
[16/55] 40/40 assigned
[17/55] 40/40 assigned
[18/55] 40/40 assigned
[19/55] 40/40 assigned
[20/55] 40/40 assigned
[21/55] 40/40 assigned
[22/55] 40/40 assigned
[23/55] 40/40 assigned
[24/55] 40/40 assigned
[25/55] 40/40 assigned
[26/55] 40/40 assigned
[27/55] 40/40 assigned
[28/55] 40/40 assigned
[29/55] 40/40 assigned
[30/55] 40/40 assigned
[31/55] 40/40 assigned
[32/55] 40/40 assigned
[33/55] 40/40 assigned
[34/55] 40/40 assigned
[35/55] 40/40 assigned
[36/55] 40/40 assigned
[37/55] 40/40 assigned
[38/55] 40/40 assigned
[39/55] 40/40 assigned
[40/55] 40/40 assigned
[41/55] 40/40 assigned
[42/55] 40/40 assigned
[43/55] 40/40 assigned
[44/55] 40/40 assigned
[45/55] 40/40 assigned
[46/55] 40/40 assigned
[47/55] 40/40 assigned
[48/55] 40/40 assigned
[49/55] 40/40 assigned
[50/55] 40/40 assigned
[51/55] 40/40 assigned
[52/55] 28/28 assigned
[53/55] 40/40 assigned
[54/55] 40/40 assigned
[55/55] 40/40 assigned
Done. 2188 written, 0 missing, 0 batches failed; call again to retry.

### 5c. Combined table

One row per surprise across discovery, train_rest and test, saved to `data/surprise/surprises_v2.csv`. The checks below are descriptive only; no returns are used.

In [42]:
surprises = dataset.build_surprise_frame(split, FROZEN)
surprises.to_csv(dataset.surprises_path(FROZEN), index=False)

events_with_rows = set(surprises["event_id"])
summary = pd.DataFrame({
    name: {
        "events in set": len(evs),
        "events extracted": len({r["event_id"] for r in extraction.load_extractions(data.extractions_path(name))} & {e["event_id"] for e in evs}),
        "events with no surprise": sum(e["event_id"] not in events_with_rows for e in evs),
        "surprises": int((surprises["split"] == name).sum()),
        "unassigned": int(((surprises["split"] == name) & surprises["dimension"].isna()).sum()),
        "other": int(((surprises["split"] == name) & (surprises["dimension"] == "other")).sum()),
    }
    for name, evs in sets.items()
})
display(summary)
surprises.head()

                         discovery  train_rest  test
events in set                  500         576   289
events extracted               500         576   289
events with no surprise          0           0    18
surprises                     3895        4448  2188
unassigned                       0           0     0
other                            1           3     1

,split,event_id,ticker,event_datetime,car1,earnings_surprise,item_id,position,n_items,dimension,dimension_name,direction,magnitude,expectation_source,description,fact_evidence,expectation_evidence,taxonomy_version,extraction_model
0,discovery,ea_QMCO_Q1_2027,QMCO,2026-08-10T21:00:00+00:00,0.649427,0.03056,ea_QMCO_Q1_2027#0,0,8,operating_profitability,"Operating profit, margins, and returns",positive,large,preview,"QMCO reported adjusted EBITDA of $8 million, f...","“Adjusted EBITDA was a positive $8 million, $5...",“Adj. EBITDA: $1.5M ± $1M.”,v2,gpt-6-luna
1,discovery,ea_QMCO_Q1_2027,QMCO,2026-08-10T21:00:00+00:00,0.649427,0.03056,ea_QMCO_Q1_2027#1,1,8,bottom_line_earnings,EPS and bottom-line earnings,positive,large,preview,"Instead of the expected non-GAAP loss, QMCO re...",“Non-GAAP net income was $4 million ($0.18 per...,“Non-GAAP EPS: ($0.15) ± $0.10”; consensus was...,v2,gpt-6-luna
2,discovery,ea_QMCO_Q1_2027,QMCO,2026-08-10T21:00:00+00:00,0.649427,0.03056,ea_QMCO_Q1_2027#2,2,8,revenue,Reported revenue and sales,positive,moderate,preview,"Revenue came in at $80.8 million, above both t...",“Q1 FY2027 revenue was $80.8 million … exceedi...,“Consensus sits exactly on the guidance midpoi...,v2,gpt-6-luna
3,discovery,ea_QMCO_Q1_2027,QMCO,2026-08-10T21:00:00+00:00,0.649427,0.03056,ea_QMCO_Q1_2027#3,3,8,operating_profitability,"Operating profit, margins, and returns",positive,moderate,preview,"GAAP gross margin reached 39.3%, above the pre...","“GAAP gross margin reached 39.3%, up 360 basis...",The preview calculated “~38% gross margin” imp...,v2,gpt-6-luna
4,discovery,ea_QMCO_Q1_2027,QMCO,2026-08-10T21:00:00+00:00,0.649427,0.03056,ea_QMCO_Q1_2027#4,4,8,forward_guidance,Financial and operating outlook,positive,moderate,preview,Q2 revenue guidance is approximately $82 milli...,“Q2 FY2027 revenue guidance is approximately $...,The preview said “a Q2 guide below ~$78M puts ...,v2,gpt-6-luna

## 6. Event-level features

One row per event (1,076 train, 289 test); discovery and train_rest are both labelled **train**. Built from `surprises_v2.csv` by `features.build_event_features` and saved to `data/surprise/features_v2.csv`.

- **Per dimension (45):** `net_w__<dim>` = Σ direction × magnitude (±1 × 1/2/3; mixed and unclear count 0), and its positive and negative parts `pos_w__<dim>` / `neg_w__<dim>` (net = pos − neg, so don't feed all three to an unregularized model).
- **Totals (9):** item counts by direction, `net`, `net_w`, the same over the first three items, `net_per_item`.
- **Flags and options (5):** `no_surprises` (extraction found nothing: 18 test events whose call facts are only procedural; no train event), and option-implied volatility, absolute move and 25-delta skew with `has_option_stats` (NaN when absent, about 42% coverage).
- **Target:** `target_pct`, car1's rank among all 2,362 events of 2026Q3, scaled to [0, 1].

Only train rows are inspected here; test stays untouched until the model is fixed.

In [43]:
from suprise_dim import features

surprises = pd.read_csv(dataset.surprises_path(FROZEN))
feat = features.build_event_features(surprises, split, events_by_id, tax)
feat.to_csv(features.features_path(FROZEN), index=False)
print(feat.shape, feat["split"].value_counts().to_dict())

train_feat = feat[feat["split"] == "train"]
r = train_feat.rank(numeric_only=True)
print("train Spearman with target_pct:",
      {c: round(r[c].corr(r["target_pct"]), 3) for c in ["net", "net_w", "net_first3", "net_w_first3", "net_per_item"]})
feat.head()

(1365, 71) {'train': 1076, 'test': 289}
train Spearman with target_pct: {'net': np.float64(0.443), 'net_w': np.float64(0.468), 'net_first3': np.float64(0.444), 'net_w_first3': np.float64(0.466), 'net_per_item': np.float64(0.433)}

,event_id,ticker,event_datetime,split,car1,target_pct,earnings_surprise,net_w__forward_guidance,net_w__revenue,net_w__operating_kpis,...,no_surprises,opt_implied_earnings_volatility,opt_implied_absolute_earnings_move,opt_skew_25_delta,has_option_stats,baseline__deepseek,baseline__gemini,baseline__moonshotai,baseline__openai,baseline__z-ai
0,ea_TWST_Q3_2026,TWST,2026-08-03T12:00:00+00:00,train,0.088587,0.840745,-0.003495,8,4,0,...,0,0.1529,0.1219,NaN,1,0.88,0.85,0.80,0.88,0.62
1,ea_ABTC_Q2_2026,ABTC,2026-08-03T12:30:00+00:00,train,0.044492,0.725964,-0.172101,0,0,4,...,0,0.1287,0.1026,NaN,1,0.80,0.78,0.55,0.81,0.58
2,ea_KRYS_Q2_2026,KRYS,2026-08-03T12:30:00+00:00,train,-0.098985,0.158831,-0.000293,0,-2,1,...,0,NaN,NaN,NaN,0,0.85,0.82,0.62,0.82,0.82
3,ea_MAR_Q2_2026,MAR,2026-08-03T12:30:00+00:00,train,-0.085027,0.187632,0.000376,-3,1,3,...,0,0.0441,0.0352,0.022,1,0.85,0.65,0.80,0.86,0.58
4,ea_SBH_Q3_2026,SBH,2026-08-03T12:30:00+00:00,train,0.062198,0.781872,0.001336,0,-3,-2,...,0,NaN,NaN,NaN,0,0.60,0.52,0.60,0.82,0.58